//@version=5

// ||###################################################################################||
// ||                                                                                   ||
// || Cipher DMG                                                                        ||
// || The Strat                                                                         ||
// ||     https://www.tradingview.com/script/0drMdHsO-TTM-Squeeze-Pro                   ||
// ||                                                                                   ||
// ||                                                                                   ||
// ||###################################################################################||

indicator(title="The Strat Sector Performance Monitor", shorttitle="The Strat Sector Performance Monitor", max_labels_count = 500, overlay=true)

LIGHTTRANSP = 90
AVGTRANSP = 80
HEAVYTRANSP = 70

var string _gp1 = 'Time Interval'
string i_time_interval = input.string('1D', '', inline='11', options=['1', '5', '15', '30', '60', '1D', '1W', '1M', '3M', '12M'], group=_gp1)

var string _gp2 = 'Display'
emptyTopTableRow = input.bool(true, title='Insert a blank table row at the top to gain more space', group=_gp2)
bullishColor = input.color(color.new(color.green, 0), title='Bullish Color', group=_gp2)
bearishColor = input.color(color.new(color.red, 0), title='Bearish Color', group=_gp2)
insideColor = input.color(color.new(color.white, 0), 'Inside Bar', inline='12', group=_gp2)
outsideColor = input.color(color.new(color.yellow, 0), 'Outside Bar', inline='12', group=_gp2)
tableYPositive = input.string('top', 'Panel position', inline='11', options=['top', 'middle', 'bottom'], group=_gp2)
tableXPositive = input.string('right', '', inline='11', options=['left', 'center', 'right'], group=_gp2)
indicatorTextSize = input.string('normal', 'Text Size', options=['tiny', 'small', 'normal', 'large', 'huge'], group=_gp2)
tfTableOpacity = input.int(80, title='Multi time frame table opacity', group=_gp2)

//##################################################################################################
//Candle Type
//##################################################################################################
getCandleType(_high, _high1, _low, _low1) =>
    candleType = 0

    //Higher High and Lower Low
    if _high > _high1 and _low < _low1
        candleType := 3
        candleType

    else if _high <= _high1 and _low >= _low1
        //Lower High and Higher Low
        if _high <= _high1 and _low >= _low1
            candleType := 1
            candleType
        else
            candleType := 2
            candleType
    candleType



// @function Entire Candle wick to wick is inside the previous candle.  This is considered a Scenario 1.
// It means its consolidation on a smaller timeframe  We do not want to trade things on a 1 because it has Not picked its direction.
// @param idx index to use
// @returns
isInsideCandle(int idx) =>
    high[idx] <= high[idx + 1] and low[idx] >= low[idx + 1]

//@function Candle engulfs the previous candle and is typically the larges bar.  This is considered a Scenario 3
//Most commonly 3s occur after 1
//@return
isOutsideCandle(int idx) =>
    high[idx] > high[idx + 1] and low[idx] < low[idx + 1]


//getPercentChange
getPercentChange(openPrice,closePrice) =>

    //The Percent Change will be the closePrice - openPrice / (max (openPrice, closePrice))
    percentChange = ((closePrice - openPrice) / (math.max(openPrice,closePrice)) ) * 100.0
    resultColor = openPrice >= closePrice ? bearishColor : bullishColor
    [percentChange,resultColor]

// FULL TIME FRAME CONTINUITY CODE:
//reusable function for getting detail on the security
getSecurityByTimeFrame(symbol,timeFrame) =>
    [openValue, closeValue, highValue, lowValue, timeValue] = request.security(symbol = symbol, timeframe = timeFrame, expression = [open, close, high, low, time], gaps = barmerge.gaps_off)

    [percentChange,resultColor] = getPercentChange(openValue,closeValue)
    [openValue, closeValue, highValue, lowValue, timeValue, percentChange, resultColor]


addTableRow(tcTable,symbol1,symbol2,symbol3,symbol4,symbol5,symbol6,symbol7, row) =>


    [openValue1, closeValue1, highValue1, lowValue1, timeValue1, percentChange1, resultColor1] = getSecurityByTimeFrame(symbol1,timeframe.period)
    [openValue2, closeValue2, highValue2, lowValue2, timeValue2, percentChange2, resultColor2] = getSecurityByTimeFrame(symbol2,timeframe.period)
    [openValue3, closeValue3, highValue3, lowValue3, timeValue3, percentChange3, resultColor3] = getSecurityByTimeFrame(symbol3,timeframe.period)
    [openValue4, closeValue4, highValue4, lowValue4, timeValue4, percentChange4, resultColor4] = getSecurityByTimeFrame(symbol4,timeframe.period)
    [openValue5, closeValue5, highValue5, lowValue5, timeValue5, percentChange5, resultColor5] = getSecurityByTimeFrame(symbol5,timeframe.period)
    [openValue6, closeValue6, highValue6, lowValue6, timeValue6, percentChange6, resultColor6] = getSecurityByTimeFrame(symbol6,timeframe.period)
    [openValue7, closeValue7, highValue7, lowValue7, timeValue7, percentChange7, resultColor7] = getSecurityByTimeFrame(symbol7,timeframe.period)


    table.cell(table_id = tcTable, column = 0, row = row, text = symbol1 + '\n' + str.tostring(percentChange1, '#.##') + '%', bgcolor=color.new(resultColor1, tfTableOpacity), text_color=resultColor1, text_size=size.auto, width=0)
    table.cell(table_id = tcTable, column = 1, row = row, text = symbol2 + '\n' + str.tostring(percentChange2, '#.##') + '%', bgcolor=color.new(resultColor2, tfTableOpacity), text_color=resultColor2, text_size=size.auto, width=0)
    table.cell(table_id = tcTable, column = 2, row = row, text = symbol3 + '\n' + str.tostring(percentChange3, '#.##') + '%', bgcolor=color.new(resultColor3, tfTableOpacity), text_color=resultColor3, text_size=size.auto, width=0)
    table.cell(table_id = tcTable, column = 3, row = row, text = symbol4 + '\n' + str.tostring(percentChange4, '#.##') + '%', bgcolor=color.new(resultColor4, tfTableOpacity), text_color=resultColor4, text_size=size.auto, width=0)
    table.cell(table_id = tcTable, column = 4, row = row, text = symbol5 + '\n' + str.tostring(percentChange5, '#.##') + '%', bgcolor=color.new(resultColor5, tfTableOpacity), text_color=resultColor5, text_size=size.auto, width=0)
    table.cell(table_id = tcTable, column = 5, row = row, text = symbol6 + '\n' + str.tostring(percentChange6, '#.##') + '%', bgcolor=color.new(resultColor6, tfTableOpacity), text_color=resultColor6, text_size=size.auto, width=0)
    table.cell(table_id = tcTable, column = 6, row = row, text = symbol7 + '\n' + str.tostring(percentChange7, '#.##') + '%', bgcolor=color.new(resultColor7, tfTableOpacity), text_color=resultColor7, text_size=size.auto, width=0)


//##################################################################################################
//Ticker Details
//SPY, QQQ, VXX, XBI, XHB, XLB, XLC, XLE, XLF, XLI, XLK, XLP, XLRE, XLU, XLY, XLV, XRT, XOP, IBB, IYT, TLT, SMH
//##################################################################################################

// do not show timeframes that are less than the time frame selected (it will be inaccurate)
if barstate.islast
    var table tcTable = table.new(position=position.top_right, columns = 7, rows = 25, border_width=3)

    table.cell(table_id = tcTable, column = 0, row = 0, text = '')
    table.cell(table_id = tcTable, column = 1, row = 0, text = '')
    table.cell(table_id = tcTable, column = 2, row = 0, text = '')
    table.cell(table_id = tcTable, column = 3, row = 0, text = '')
    table.cell(table_id = tcTable, column = 4, row = 0, text = '')
    table.cell(table_id = tcTable, column = 5, row = 0, text = '')
    table.cell(table_id = tcTable, column = 6, row = 0, text = '')

    addTableRow(tcTable,"SPY","QQQ","VIX","DIA","IWM","SMH","XOP",1)

    addTableRow(tcTable,"XLE","XLK","XLU","XBI","XHB","XLB","XLC",2)

    addTableRow(tcTable,"XLF","XLI","XLP","XLRE","XLU","XLY","XLV",3)

    addTableRow(tcTable,"XRT","XLU","IBB","IYT","TLT","ARKK","ARKQ",4)

    addTableRow(tcTable,"ARKW","ARKG","ARKF","ARKX","TLT","ARKK","ARKQ",5)
