//@version=5
// ||###################################################################################||
// ||                                                                                   ||
// || This moving average strategy is very easy to follow:                              ||
// ||                                                                                   ||
// || The strategy goes long when the faster SMA 50 crosses above the SMA 200.          ||
// || Orders are closed when the SMA 50 crosses below SMA 200. The strategy does not    ||
// || short.                                                                            ||
// ||                                                                                   ||
// || This simple strategy does not have any other stop loss or take profit money       ||
// || management logic.                                                                 ||
// ||                                                                                   ||
// ||###################################################################################||

//@version=5
indicator(title="Average True Range", shorttitle="ATR", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(title="Length", defval=14, minval=1)
smoothing = input.string(title="Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA"])
ma_function(source, length) =>
	switch smoothing
		"RMA" => ta.rma(source, length)
		"SMA" => ta.sma(source, length)
		"EMA" => ta.ema(source, length)
		=> ta.wma(source, length)
plot(ma_function(ta.tr(true), length), title = "ATR", color=color.new(#B71C1C, 0))
