//@version=5
// ||###################################################################################||
// ||                                                                                   ||
// ||
// ||  Bollinger Band with RSI Strategy
// ||
// ||  https://www.tradingview.com/script/pKOaIHpb-Bollinger-Band-with-RSI/
// ||                                                                                   ||
// ||###################################################################################||


strategy(title='Bollinger Band with RSI', shorttitle='Bollinger Band with RSI', format=format.price, precision=2, pyramiding=50, initial_capital=10000, calc_on_order_fills=false, calc_on_every_tick=true, default_qty_type=strategy.cash, default_qty_value=1000, currency='USD')
len = input.int(14, minval=1, title='Length')
src = input(close, 'Source')
up = ta.rma(math.max(ta.change(src), 0), len)
down = ta.rma(-math.min(ta.change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - 100 / (1 + up / down)
plot(rsi, 'RSI', color=color.new(#8E1599, 0))
band1 = hline(70, 'Upper Band', color=#C0C0C0)
band0 = hline(30, 'Lower Band', color=#C0C0C0)
fill(band1, band0, color=color.new(#9915FF, 90), title='Background')

length_bb = input.int(20, title='BB Length', minval=1)
mult = input.float(2.0, minval=0.001, maxval=50, title='BB StdDev')
basis = ta.sma(src, length_bb)
dev = mult * ta.stdev(src, length_bb)
upper = basis + dev
lower = basis - dev
offset = input.int(0, 'BB Offset', minval=-500, maxval=500)


Plot_PnL = input(title='Plot Cummulative PnL', defval=false)
Plot_Pos = input(title='Plot Current Position Size', defval=false)

long_tp_inp = input.float(10, title='Long Take Profit %', step=0.1) / 100
long_sl_inp = input.float(25, title='Long Stop Loss %', step=0.1) / 100
// Take profit/stop loss
long_take_level = strategy.position_avg_price * (1 + long_tp_inp)
long_stop_level = strategy.position_avg_price * (1 - long_sl_inp)

entry_long = rsi < 30 and src < lower
exit_long = rsi > 70

plotshape(entry_long, style=shape.labelup, color=color.new(color.green, 0), location=location.bottom, text='L', textcolor=color.new(color.white, 0), title='LONG_ORDER')
plotshape(exit_long, style=shape.labeldown, color=color.new(color.red, 0), location=location.top, text='S', textcolor=color.new(color.white, 0), title='SHORT_ORDER')

strategy.entry('Long', strategy.long, when=entry_long)
strategy.exit('TP/SL', 'Long', limit=long_take_level, stop=long_stop_level)
strategy.close('Long', when=exit_long, comment='Exit')
plot(Plot_PnL ? strategy.equity - strategy.initial_capital : na, title='PnL', color=color.new(color.red, 0))
plot(Plot_Pos ? strategy.position_size : na, title='open_position', color=color.new(color.fuchsia, 0))

