//@version=5
// ||###################################################################################||
// ||                                                                                   ||
// || This moving average strategy is very easy to follow:                              ||
// ||                                                                                   ||
// || The strategy goes long when the faster SMA 50 crosses above the SMA 200.          ||
// || Orders are closed when the SMA 50 crosses below SMA 200. The strategy does not    ||
// || short.                                                                            ||
// ||                                                                                   ||
// || This simple strategy does not have any other stop loss or take profit money       ||
// || management logic.                                                                 ||
// ||                                                                                   ||
// ||###################################################################################||

strategy("Golden Cross using SMA 200 Long Only Moving Average Strategy", shorttitle="Golden Cross Strategy", overlay=true)

// Input
switch1 = input(true, title="Enable Bar Color?")
switch2 = input(false, title="Show Fast Moving Average")
switch3 = input(true, title="Show Slow Moving Average")

movingaverage_fast = ta.sma(close, input(50))
movingaverage_slow = ta.sma(close, input(200))

// Calculation
bullish_cross = ta.crossover(movingaverage_fast, movingaverage_slow)
bearish_cross = ta.crossunder(movingaverage_fast, movingaverage_slow)

// Strategy
if bullish_cross
    strategy.entry("long", strategy.long)

strategy.close("long", when=bearish_cross)

// Colors
bartrendcolor = close > movingaverage_fast and close > movingaverage_slow and ta.change(movingaverage_slow) > 0 ? color.green : close < movingaverage_fast and close < movingaverage_slow and ta.change(movingaverage_slow) < 0 ? color.red : color.blue
barcolor(switch1 ? bartrendcolor : na)

// Output
plot(switch2 ? movingaverage_fast : na, color=ta.change(movingaverage_fast) > 0 ? color.green : color.red, linewidth=3)
plot(switch3 ? movingaverage_slow : na, color=ta.change(movingaverage_slow) > 0 ? color.green : color.red, linewidth=3)

