//@version=5
// ||###################################################################################||
// ||                                                                                   ||
// || This moving average strategy is very easy to follow:                              ||
// ||                                                                                   ||
// || The strategy goes long when the faster SMA 50 crosses above the SMA 200.          ||
// || Orders are closed when the SMA 50 crosses below SMA 200. The strategy does not    ||
// || short.                                                                            ||
// ||                                                                                   ||
// || This simple strategy does not have any other stop loss or take profit money       ||
// || management logic.                                                                 ||
// ||                                                                                   ||
// ||###################################################################################||

strategy("Golden Cross using SMA 200 Long Only Moving Average Strategy", shorttitle="Golden Cross Strategy", overlay=true)

// Setup Date for Strategy
fromMonth = input.int(defval=1, title='From Month', minval=1, maxval=12)
fromDay = input.int(defval=1, title='From Day', minval=1, maxval=31)
fromYear = input.int(defval=2015, title='From Year', minval=1970)
thruMonth = input.int(defval=1, title='Thru Month', minval=1, maxval=12)
thruDay = input.int(defval=1, title='Thru Day', minval=1, maxval=31)
thruYear = input.int(defval=2022, title='Thru Year', minval=1970)

// === INPUT SHOW PLOT ===
showDate = input(defval=true, title='Show Date Range')

// === FUNCTION EXAMPLE ===
start = timestamp(fromYear, fromMonth, fromDay, 00, 00)  // backtest start window
finish = timestamp(thruYear, thruMonth, thruDay, 23, 59)  // backtest finish window
window() =>  // create function "within window of time"
    time >= start and time <= finish ? true : false



// Input
switch1 = input(true, title="Enable Bar Color?")
switch2 = input(false, title="Show Fast Moving Average")
switch3 = input(true, title="Show Slow Moving Average")

movingaverage_fast = ta.ema(close, input(50))
movingaverage_slow = ta.ema(close, input(200))

// Calculation
bullish_cross = ta.crossover(movingaverage_fast, movingaverage_slow)
bearish_cross = ta.crossunder(movingaverage_fast, movingaverage_slow)

// Strategy
if bullish_cross
    strategy.entry("long", strategy.long, qty=100, when=window())

strategy.close("long",qty=100, when=bearish_cross, when=window())

// Colors
bartrendcolor = close > movingaverage_fast and close > movingaverage_slow and ta.change(movingaverage_slow) > 0 ? color.green : close < movingaverage_fast and close < movingaverage_slow and ta.change(movingaverage_slow) < 0 ? color.red : color.blue
barcolor(switch1 ? bartrendcolor : na)

//Highlight the area which is being back tested
bgcolor(color=showDate and window() ? color.gray : na, transp=90)  // plot "within window of time"

// Output
//plot(switch2 ? movingaverage_fast : na, color=ta.change(movingaverage_fast) > 0 ? color.green : color.red, linewidth=3)
plot(switch3 ? movingaverage_slow : na, color=ta.change(movingaverage_slow) > 0 ? color.green : color.red, linewidth=3) //Plot 200 day moving average

