//@version=5
// ||###################################################################################||
// ||                                                                                   ||
// ||
// ||  Stochastic Slow + Relative Strength Index, Double Strategy
// ||
// ||  This strategy uses the RSI indicator together with the Bollinger Bands
// ||  to buy when the price is below the lower Bollinger Band (and to close the
// ||  long trade when this value is above the upper Bollinger band).
// ||
// ||  This simple strategy only longs when both the RSI and the Bollinger Bands
// ||  indicators are at the same time in a oversold condition.
// ||
// || In this new version 1.2 the strategy was simplified by going long-only, which made it more successful in backtesting.
// ||
// || https://www.tradingview.com/script/HDSdFMa3-Bollinger-RSI-Double-Strategy-Long-Only-by-ChartArt-v1-2/
// ||                                                                                   ||
// ||###################################################################################||

strategy('Bollinger and RSI Strategy Long-Only', shorttitle='Bollinger and RSI Strategy Long-Only', overlay=true)

///////////// RSI
RSIlength = input(6, title='RSI Period Length')
RSIoverSold = 50
RSIoverBought = 50
price = close
vrsi = ta.rsi(price, RSIlength)


// === INPUT BACKTEST RANGE ===
fromMonth = input.int(defval=1, title='From Month', minval=1, maxval=12)
fromDay = input.int(defval=1, title='From Day', minval=1, maxval=31)
fromYear = input.int(defval=2019, title='From Year', minval=1970)
thruMonth = input.int(defval=1, title='Thru Month', minval=1, maxval=12)
thruDay = input.int(defval=1, title='Thru Day', minval=1, maxval=31)
thruYear = input.int(defval=2022, title='Thru Year', minval=1970)

// === INPUT SHOW PLOT ===
showDate = input(defval=true, title='Show Date Range')


// === FUNCTION EXAMPLE ===
start = timestamp(fromYear, fromMonth, fromDay, 00, 00)  // backtest start window
finish = timestamp(thruYear, thruMonth, thruDay, 23, 59)  // backtest finish window
window() =>  // create function "within window of time"
    time >= start and time <= finish ? true : false


///////////// Bollinger Bands
BBlength = input.int(200, minval=1, title='Bollinger Period Length')
BBmult = 2  // input(2.0, minval=0.001, maxval=50,title="Bollinger Bands Standard Deviation")
BBbasis = ta.sma(price, BBlength)
BBdev = BBmult * ta.stdev(price, BBlength)
BBupper = BBbasis + BBdev
BBlower = BBbasis - BBdev
source = close
buyEntry = ta.crossover(source, BBlower)
sellEntry = ta.crossunder(source, BBupper)
plot(BBbasis, color=color.new(color.blue, 0), title='Bollinger Bands SMA Basis Line')
p1 = plot(BBupper, color=color.new(color.green, 0), title='Bollinger Bands Upper Line')
p2 = plot(BBlower, color=color.new(color.red, 0), title='Bollinger Bands Lower Line')
fill(p1, p2, transp=90)


///////////// Colors
switch1 = input(true, title='Enable Bar Color?')
switch2 = input(true, title='Enable Background Color?')
TrendColor = RSIoverBought and price[1] > BBupper and price < BBupper and BBbasis < BBbasis[1] ? color.red : RSIoverSold and price[1] < BBlower and price > BBlower and BBbasis > BBbasis[1] ? color.green : na
barcolor(switch1 ? TrendColor : na)
bgcolor(switch2 ? TrendColor : na, transp=50)
bgcolor(color=showDate and window() ? color.aqua : na, transp=90)  // plot "within window of time"

///////////// RSI + Bollinger Bands Strategy
long = ta.crossover(vrsi, RSIoverSold) and ta.crossover(source, BBlower)
close_long = ta.crossunder(vrsi, RSIoverBought) and ta.crossunder(source, BBupper)

if not na(vrsi)

    if long
        strategy.entry('RSI_BB', strategy.long, when=window(), stop=BBlower, oca_type=strategy.oca.cancel, comment='RSI_BB')
    else
        strategy.cancel(id='RSI_BB',when=window())

    if close_long
        strategy.close('RSI_BB',when=window())


//plot(strategy.equity, title="equity", color=red, linewidth=2, style=areabr)

