//@version=5
// ||###################################################################################||
// ||                                                                                   ||
// ||  Moving Average Cross                                                             ||
// ||                                                                                   ||
// ||###################################################################################||

strategy('Moving Average Cross', overlay=true)

ema20 = ta.ema(close, 20)
ema50 = ta.ema(close, 50)

long = ema20 > ema50
short = ema20 < ema50

longcondition = long and long[10] and not long[11]
shortcondition = short and short[10] and not short[11]

closelong = ema20 < ema50 and not long[11]
closeshort = ema20 > ema50 and not short[11]

plot(ema20, title='20', color=color.new(color.green, 0), linewidth=3)
plot(ema50, title='50', color=color.new(color.red, 0), linewidth=2)

start = timestamp(2015, 6, 1, 0, 0)
end = timestamp(2021, 6, 1, 0, 0)

if time >= start and time <= end
    strategy.entry('Long', strategy.long, 1000.0, when=longcondition)
    strategy.entry('Short', strategy.short, 1000.0, when=shortcondition)

strategy.close('Long', when=closeshort)
strategy.close('Short', when=closelong)

