// ||###################################################################################||
// ||                                                                                   ||
// || Candle Stick Patterns                                                             ||
// || https://www.tradingview.com/script/4aaRYSWi-Sideways-detection-bollinger-bands
// ||                                                                                   ||
// ||                                                                                   ||
// ||###################################################################################||
//@version=4
//@author exlux99
study("Sideways detection", overlay=true)

//INPUTS

source       = input(title="Source", type=input.source, defval=close)
length       = input(50, minval=1, title="Length")
multi        = input(4.0, minval=0.1,  title="StdDev")

//CALCULATIONS
average      = sma(source, length)
dev          = multi * stdev(source, length)
upperx       = average + dev
lowerx       = average - dev
bb_ratio          = (source - lowerx)/(upperx - lowerx)

//SMOOTHING
bb_smooth         = input(title="Signal Smoothing", type=input.integer, defval=20)
bb_ratio_std         = stdev(bb_ratio, bb_smooth)
bb_ratio_std_thresh  = input(title="Std. threshold", type=input.float, defval=0.05, step=0.01)

//TREND VS SIDEWAYS
trending     = bb_ratio < 0.0 or bb_ratio > 1.0
trending_2   =  bb_ratio_std >= bb_ratio_std_thresh

bgcolor( trending or trending_2 ? color.lime : color.red, transp=70)
