//@version=4
// ||###################################################################################||
// ||                                                                                   ||
// || https://www.tradingview.com/script/1vqh39EX-Strat-Assistant-Screener/
// ||                                                                                   ||
// ||                                                                                   ||
// ||###################################################################################||



// CONSTANTS
_labelShooterText   = "SHOOTER List\n============\n"
_labelHammerText    = "HAMMER List\n============\n"
_labelInsideText    = "INSIDE List\n============\n"
_labelTwoUpText     = "2 UP List\n============\n"
_labelTwoDownText   = "2 DOWN List\n============\n"
_labelOutsideText   = "OUTSIDE List\n============\n"
_labelGreenText     = "----GREEN----\n"
_labelRedText       = "-----RED-----\n"
_newLineText        = "\n"
_labelTextColor     = color.white
_labelTextAlign     = text.align_left
_labelYIndex        = 0
_labelXIndex        = bar_index
_labelYLoc          = yloc.price
_labelStyle         = label.style_labelup
_inputTypeDefault   = input.symbol
_isGreenCandleResult  = 12
_isRedCandleResult    = 11

// VARIABLES (default blank texts for each label)
insideText = ""
shooterGreenText = ""
shooterRedText = ""
hammerGreenText  = ""
hammerRedText  = ""
twoUpGreenText   = ""
twoUpRedText   = ""
twoDownGreenText = ""
twoDownRedText = ""
outsideGreenText = ""
outsideRedText = ""

// INPUTS
_securityTimeFrame      = input(title = "Security/Screener Time Frame", type = input.resolution, defval="D")
_labelHeaderText        = "Strat Assistant\nScreener: " + _securityTimeFrame + "\n\n"
_actionWickPercentage   = input(title="Action Wick Percentage", type=input.float, defval=.75)
_labelIndexOffset       = input(title="Label Index Offset Factor", type=input.integer, defval=10)
_activeDataSet          = input(title="Which Data Set is Active?", type=input.string, defval="1) Main Sector/ETF/Future Top 40", options=["1) Main Sector/ETF/Future Top 40", "2) Market Cap Top 40", "3) ARKK Top 40", "4) International Top 40", "5) Custom Input Set1", "6) Custom Input Set2"])

// STUDY
study("Strat Assistant Screener", shorttitle = 'Strat Assistant Screener', overlay = false)

// SECURITIES (limit of 40)
// predefined data list
main_01= input('ARKK',  type=_inputTypeDefault, group='Main 40',        inline='1',    title='Stk_01')
main_02= input('BOND',  type=_inputTypeDefault, group='Main 40',        inline='1',    title='Stk_02')
main_03= input('DIA',   type=_inputTypeDefault, group='Main 40',        inline='2',    title='Stk_03')
main_04= input('ES1!',  type=_inputTypeDefault, group='Main 40',        inline='2',    title='Stk_04')
main_05= input('GLD',   type=_inputTypeDefault, group='Main 40',        inline='3',    title='Stk_05')
main_06= input('IBB',   type=_inputTypeDefault, group='Main 40',        inline='3',    title='Stk_06')
main_07= input('IJH',   type=_inputTypeDefault, group='Main 40',        inline='4',    title='Stk_07')
main_08= input('ITB',   type=_inputTypeDefault, group='Main 40',        inline='4',    title='Stk_08')
main_09= input('IVV',   type=_inputTypeDefault, group='Main 40',        inline='5',    title='Stk_09')
main_10= input('IWM',   type=_inputTypeDefault, group='Main 40',        inline='5',    title='Stk_10')
main_11= input('IYE',   type=_inputTypeDefault, group='Main 40',        inline='6',    title='Stk_11')
main_12= input('IYR',   type=_inputTypeDefault, group='Main 40',        inline='6',    title='Stk_12')
main_13= input('KBE',   type=_inputTypeDefault, group='Main 40',        inline='7',    title='Stk_13')
main_14= input('KRE',   type=_inputTypeDefault, group='Main 40',        inline='7',    title='Stk_14')
main_15= input('NQ1!',  type=_inputTypeDefault, group='Main 40',        inline='8',    title='Stk_15')
main_16= input('OIH',   type=_inputTypeDefault, group='Main 40',        inline='8',    title='Stk_16')
main_17= input('QQQ',   type=_inputTypeDefault, group='Main 40',        inline='9',    title='Stk_17')
main_18= input('RTY1!', type=_inputTypeDefault, group='Main 40',        inline='9',    title='Stk_18')
main_19= input('SMH',   type=_inputTypeDefault, group='Main 40',        inline='10',   title='Stk_19')
main_20= input('SPY',   type=_inputTypeDefault, group='Main 40',        inline='10',   title='Stk_20')
main_21= input('TLT',   type=_inputTypeDefault, group='Main 40',        inline='11',   title='Stk_21')
main_22= input('VIX',   type=_inputTypeDefault, group='Main 40',        inline='11',   title='Stk_22')
main_23= input('VNQ',   type=_inputTypeDefault, group='Main 40',        inline='12',   title='Stk_23')
main_24= input('VXUS',  type=_inputTypeDefault, group='Main 40',        inline='12',   title='Stk_24')
main_25= input('XHB',   type=_inputTypeDefault, group='Main 40',        inline='13',   title='Stk_25')
main_26= input('XLB',   type=_inputTypeDefault, group='Main 40',        inline='13',   title='Stk_26')
main_27= input('XLC',   type=_inputTypeDefault, group='Main 40',        inline='14',   title='Stk_27')
main_28= input('XLE',   type=_inputTypeDefault, group='Main 40',        inline='14',   title='Stk_28')
main_29= input('XLF',   type=_inputTypeDefault, group='Main 40',        inline='15',   title='Stk_29')
main_30= input('XLI',   type=_inputTypeDefault, group='Main 40',        inline='15',   title='Stk_30')
main_31= input('XLK',   type=_inputTypeDefault, group='Main 40',        inline='16',   title='Stk_31')
main_32= input('XLP',   type=_inputTypeDefault, group='Main 40',        inline='16',   title='Stk_32')
main_33= input('XLRE',  type=_inputTypeDefault, group='Main 40',        inline='17',   title='Stk_33')
main_34= input('XLU',   type=_inputTypeDefault, group='Main 40',        inline='17',   title='Stk_34')
main_35= input('XLV',   type=_inputTypeDefault, group='Main 40',        inline='18',   title='Stk_35')
main_36= input('XLY',   type=_inputTypeDefault, group='Main 40',        inline='18',   title='Stk_36')
main_37= input('XME',   type=_inputTypeDefault, group='Main 40',        inline='19',   title='Stk_37')
main_38= input('XOP',   type=_inputTypeDefault, group='Main 40',        inline='19',   title='Stk_38')
main_39= input('XRT',   type=_inputTypeDefault, group='Main 40',        inline='20',   title='Stk_39')
main_40= input('XTL',   type=_inputTypeDefault, group='Main 40',        inline='20',   title='Stk_40')

mcap_01= input('AAPL',  type=_inputTypeDefault, group='Market Cap 40',  inline='1',  title='Stk_01')
mcap_02= input('MSFT',  type=_inputTypeDefault, group='Market Cap 40',  inline='1',  title='Stk_02')
mcap_03= input('AMZN',  type=_inputTypeDefault, group='Market Cap 40',  inline='2',  title='Stk_03')
mcap_04= input('GOOG',  type=_inputTypeDefault, group='Market Cap 40',  inline='2',  title='Stk_04')
mcap_05= input('FB',    type=_inputTypeDefault, group='Market Cap 40',  inline='3',  title='Stk_05')
mcap_06= input('BRK.A', type=_inputTypeDefault, group='Market Cap 40',  inline='3',  title='Stk_06')
mcap_07= input('TSLA',  type=_inputTypeDefault, group='Market Cap 40',  inline='4',  title='Stk_07')
mcap_08= input('V',     type=_inputTypeDefault, group='Market Cap 40',  inline='4',  title='Stk_08')
mcap_09= input('JPM',   type=_inputTypeDefault, group='Market Cap 40',  inline='5',  title='Stk_09')
mcap_10= input('NVDA',  type=_inputTypeDefault, group='Market Cap 40',  inline='5',  title='Stk_10')
mcap_11= input('JNJ',   type=_inputTypeDefault, group='Market Cap 40',  inline='6',  title='Stk_11')
mcap_12= input('WMT',   type=_inputTypeDefault, group='Market Cap 40',  inline='6',  title='Stk_12')
mcap_13= input('UNH',   type=_inputTypeDefault, group='Market Cap 40',  inline='7',  title='Stk_13')
mcap_14= input('MA',    type=_inputTypeDefault, group='Market Cap 40',  inline='7',  title='Stk_14')
mcap_15= input('PYPL',  type=_inputTypeDefault, group='Market Cap 40',  inline='8',  title='Stk_15')
mcap_16= input('PG',    type=_inputTypeDefault, group='Market Cap 40',  inline='8',  title='Stk_16')
mcap_17= input('HD',    type=_inputTypeDefault, group='Market Cap 40',  inline='9',  title='Stk_17')
mcap_18= input('DIS',   type=_inputTypeDefault, group='Market Cap 40',  inline='9',  title='Stk_18')
mcap_19= input('BAC',   type=_inputTypeDefault, group='Market Cap 40',  inline='10', title='Stk_19')
mcap_20= input('ADBE',  type=_inputTypeDefault, group='Market Cap 40',  inline='10', title='Stk_20')
mcap_21= input('CMCSA', type=_inputTypeDefault, group='Market Cap 40',  inline='11', title='Stk_21')
mcap_22= input('NKE',   type=_inputTypeDefault, group='Market Cap 40',  inline='11', title='Stk_22')
mcap_23= input('ORCL',  type=_inputTypeDefault, group='Market Cap 40',  inline='12', title='Stk_23')
mcap_24= input('KO',    type=_inputTypeDefault, group='Market Cap 40',  inline='12', title='Stk_24')
mcap_25= input('XOM',   type=_inputTypeDefault, group='Market Cap 40',  inline='13', title='Stk_25')
mcap_26= input('NFLX',  type=_inputTypeDefault, group='Market Cap 40',  inline='13', title='Stk_26')
mcap_27= input('VZ',    type=_inputTypeDefault, group='Market Cap 40',  inline='14', title='Stk_27')
mcap_28= input('CSCO',  type=_inputTypeDefault, group='Market Cap 40',  inline='14', title='Stk_28')
mcap_29= input('PFE',   type=_inputTypeDefault, group='Market Cap 40',  inline='15', title='Stk_29')
mcap_30= input('LLY',   type=_inputTypeDefault, group='Market Cap 40',  inline='15', title='Stk_30')
mcap_31= input('INTC',  type=_inputTypeDefault, group='Market Cap 40',  inline='16', title='Stk_31')
mcap_32= input('CRM',   type=_inputTypeDefault, group='Market Cap 40',  inline='16', title='Stk_32')
mcap_33= input('PEP',   type=_inputTypeDefault, group='Market Cap 40',  inline='17', title='Stk_33')
mcap_34= input('ABT',   type=_inputTypeDefault, group='Market Cap 40',  inline='17', title='Stk_34')
mcap_35= input('ACN',   type=_inputTypeDefault, group='Market Cap 40',  inline='18', title='Stk_35')
mcap_36= input('ABBV',  type=_inputTypeDefault, group='Market Cap 40',  inline='18', title='Stk_36')
mcap_37= input('TMO',   type=_inputTypeDefault, group='Market Cap 40',  inline='19', title='Stk_37')
mcap_38= input('DHR',   type=_inputTypeDefault, group='Market Cap 40',  inline='19', title='Stk_38')
mcap_39= input('T',     type=_inputTypeDefault, group='Market Cap 40',  inline='20', title='Stk_39')
mcap_40= input('MRK',   type=_inputTypeDefault, group='Market Cap 40',  inline='20', title='Stk_40')

arkk_01= input('BEAM',  type=_inputTypeDefault, group='ARKK Set1',     inline='1',     title='Stk_01')
arkk_02= input('BLI',   type=_inputTypeDefault, group='ARKK Set1',     inline='1',     title='Stk_02')
arkk_03= input('COIN',  type=_inputTypeDefault, group='ARKK Set1',     inline='2',     title='Stk_03')
arkk_04= input('CRSP',  type=_inputTypeDefault, group='ARKK Set1',     inline='2',     title='Stk_04')
arkk_05= input('DKNG',  type=_inputTypeDefault, group='ARKK Set1',     inline='3',     title='Stk_05')
arkk_06= input('DOCU',  type=_inputTypeDefault, group='ARKK Set1',     inline='3',     title='Stk_06')
arkk_07= input('EDIT',  type=_inputTypeDefault, group='ARKK Set1',     inline='4',     title='Stk_07')
arkk_08= input('EXAS',  type=_inputTypeDefault, group='ARKK Set1',     inline='4',     title='Stk_08')
arkk_09= input('FATE',  type=_inputTypeDefault, group='ARKK Set1',     inline='5',     title='Stk_09')
arkk_10= input('IOVA',  type=_inputTypeDefault, group='ARKK Set1',     inline='5',     title='Stk_10')
arkk_11= input('IRDM',  type=_inputTypeDefault, group='ARKK Set1',     inline='6',     title='Stk_11')
arkk_12= input('MCRB',  type=_inputTypeDefault, group='ARKK Set1',     inline='6',     title='Stk_12')
arkk_13= input('NTDOY', type=_inputTypeDefault, group='ARKK Set1',     inline='7',     title='Stk_13')
arkk_14= input('NTLA',  type=_inputTypeDefault, group='ARKK Set1',     inline='7',     title='Stk_14')
arkk_15= input('NVTA',  type=_inputTypeDefault, group='ARKK Set1',     inline='8',     title='Stk_15')
arkk_16= input('PACB',  type=_inputTypeDefault, group='ARKK Set1',     inline='8',     title='Stk_16')
arkk_17= input('PATH',  type=_inputTypeDefault, group='ARKK Set1',     inline='9',     title='Stk_17')
arkk_18= input('PD',    type=_inputTypeDefault, group='ARKK Set1',     inline='9',     title='Stk_18')
arkk_19= input('PLTR',  type=_inputTypeDefault, group='ARKK Set1',     inline='10',    title='Stk_19')
arkk_20= input('PRLB',  type=_inputTypeDefault, group='ARKK Set1',     inline='10',    title='Stk_20')
arkk_21= input('ROKU',  type=_inputTypeDefault, group='ARKK Set1',     inline='11',    title='Stk_21')
arkk_22= input('SE',    type=_inputTypeDefault, group='ARKK Set1',     inline='11',    title='Stk_22')
arkk_23= input('SHOP',  type=_inputTypeDefault, group='ARKK Set1',     inline='12',    title='Stk_23')
arkk_24= input('SKLZ',  type=_inputTypeDefault, group='ARKK Set1',     inline='12',    title='Stk_24')
arkk_25= input('SPOT',  type=_inputTypeDefault, group='ARKK Set1',     inline='13',    title='Stk_25')
arkk_26= input('SQ',    type=_inputTypeDefault, group='ARKK Set1',     inline='13',    title='Stk_26')
arkk_27= input('TDOC',  type=_inputTypeDefault, group='ARKK Set1',     inline='14',    title='Stk_27')
arkk_28= input('TER',   type=_inputTypeDefault, group='ARKK Set1',     inline='14',    title='Stk_28')
arkk_29= input('TRMB',  type=_inputTypeDefault, group='ARKK Set1',     inline='15',    title='Stk_29')
arkk_30= input('TSLA',  type=_inputTypeDefault, group='ARKK Set1',     inline='15',    title='Stk_30')
arkk_31= input('TSP',   type=_inputTypeDefault, group='ARKK Set1',     inline='16',    title='Stk_31')
arkk_32= input('TWLO',  type=_inputTypeDefault, group='ARKK Set1',     inline='16',    title='Stk_32')
arkk_33= input('TWOU',  type=_inputTypeDefault, group='ARKK Set1',     inline='17',    title='Stk_33')
arkk_34= input('TWST',  type=_inputTypeDefault, group='ARKK Set1',     inline='17',    title='Stk_34')
arkk_35= input('TWTR',  type=_inputTypeDefault, group='ARKK Set1',     inline='18',    title='Stk_35')
arkk_36= input('TXG',   type=_inputTypeDefault, group='ARKK Set1',     inline='18',    title='Stk_36')
arkk_37= input('U',     type=_inputTypeDefault, group='ARKK Set1',     inline='19',    title='Stk_37')
arkk_38= input('VCYT',  type=_inputTypeDefault, group='ARKK Set1',     inline='19',    title='Stk_38')
arkk_39= input('Z',     type=_inputTypeDefault, group='ARKK Set1',     inline='20',    title='Stk_39')
arkk_40= input('ZM',    type=_inputTypeDefault, group='ARKK Set1',     inline='20',    title='Stk_40')

intl_01= input('APTV',  type=_inputTypeDefault,group='International Top 40', inline='1',    title='Stk_01')
intl_02= input('BABA',  type=_inputTypeDefault,group='International Top 40', inline='1',    title='Stk_02')
intl_03= input('BEKE',  type=_inputTypeDefault,group='International Top 40', inline='2',    title='Stk_03')
intl_04= input('BGNE',  type=_inputTypeDefault,group='International Top 40', inline='2',    title='Stk_04')
intl_05= input('BIDU',  type=_inputTypeDefault,group='International Top 40', inline='3',    title='Stk_05')
intl_06= input('BILI',  type=_inputTypeDefault,group='International Top 40', inline='3',    title='Stk_06')
intl_07= input('CHKP',  type=_inputTypeDefault,group='International Top 40', inline='4',    title='Stk_07')
intl_08= input('CPNG',  type=_inputTypeDefault,group='International Top 40', inline='4',    title='Stk_08')
intl_09= input('CRSP',  type=_inputTypeDefault,group='International Top 40', inline='5',    title='Stk_09')
intl_10= input('CVAC',  type=_inputTypeDefault,group='International Top 40', inline='5',    title='Stk_10')
intl_11= input('CYBR',  type=_inputTypeDefault,group='International Top 40', inline='6',    title='Stk_11')
intl_12= input('DIDI',  type=_inputTypeDefault,group='International Top 40', inline='6',    title='Stk_12')
intl_13= input('FERG',  type=_inputTypeDefault,group='International Top 40', inline='7',    title='Stk_13')
intl_14= input('FTCH',  type=_inputTypeDefault,group='International Top 40', inline='7',    title='Stk_14')
intl_15= input('FUTU',  type=_inputTypeDefault,group='International Top 40', inline='8',    title='Stk_15')
intl_16= input('FVRR',  type=_inputTypeDefault,group='International Top 40', inline='8',    title='Stk_16')
intl_17= input('HTHT',  type=_inputTypeDefault,group='International Top 40', inline='9',    title='Stk_17')
intl_18= input('ICLR',  type=_inputTypeDefault,group='International Top 40', inline='9',    title='Stk_18')
intl_19= input('JD',    type=_inputTypeDefault,group='International Top 40', inline='10',   title='Stk_19')
intl_20= input('LI',    type=_inputTypeDefault,group='International Top 40', inline='10',   title='Stk_20')
intl_21= input('LU',    type=_inputTypeDefault,group='International Top 40', inline='11',   title='Stk_21')
intl_22= input('NIO',   type=_inputTypeDefault,group='International Top 40', inline='11',   title='Stk_22')
intl_23= input('NTES',  type=_inputTypeDefault,group='International Top 40', inline='12',   title='Stk_23')
intl_24= input('NXPI',  type=_inputTypeDefault,group='International Top 40', inline='12',   title='Stk_24')
intl_25= input('PDD',   type=_inputTypeDefault,group='International Top 40', inline='13',   title='Stk_25')
intl_26= input('QGEN',  type=_inputTypeDefault,group='International Top 40', inline='13',   title='Stk_26')
intl_27= input('SPOT',  type=_inputTypeDefault,group='International Top 40', inline='14',   title='Stk_27')
intl_28= input('STNE',  type=_inputTypeDefault,group='International Top 40', inline='14',   title='Stk_28')
intl_29= input('TCOM',  type=_inputTypeDefault,group='International Top 40', inline='15',   title='Stk_29')
intl_30= input('TEAM',  type=_inputTypeDefault,group='International Top 40', inline='15',   title='Stk_30')
intl_31= input('TLRY',  type=_inputTypeDefault,group='International Top 40', inline='16',   title='Stk_31')
intl_32= input('TME',   type=_inputTypeDefault,group='International Top 40', inline='16',   title='Stk_32')
intl_33= input('WB',    type=_inputTypeDefault,group='International Top 40', inline='17',   title='Stk_33')
intl_34= input('WIX',   type=_inputTypeDefault,group='International Top 40', inline='17',   title='Stk_34')
intl_35= input('XP',    type=_inputTypeDefault,group='International Top 40', inline='18',   title='Stk_35')
intl_36= input('XPEV',  type=_inputTypeDefault,group='International Top 40', inline='18',   title='Stk_36')
intl_37= input('YUMC',  type=_inputTypeDefault,group='International Top 40', inline='19',   title='Stk_37')
intl_38= input('YUMC',  type=_inputTypeDefault,group='International Top 40', inline='19',   title='Stk_38')
intl_39= input('ZLAB',  type=_inputTypeDefault,group='International Top 40', inline='20',   title='Stk_39')
intl_40= input('ZTO',   type=_inputTypeDefault,group='International Top 40', inline='20',   title='Stk_40')

c1_01= input('AEP',     type=_inputTypeDefault,group='Input Set1',      inline='1',     title='Stk_01')
c1_02= input('AMT',     type=_inputTypeDefault,group='Input Set1',      inline='1',     title='Stk_02')
c1_03= input('AXP',     type=_inputTypeDefault,group='Input Set1',      inline='2',     title='Stk_03')
c1_04= input('BA',      type=_inputTypeDefault,group='Input Set1',      inline='2',     title='Stk_04')
c1_05= input('BA',      type=_inputTypeDefault,group='Input Set1',      inline='3',     title='Stk_05')
c1_06= input('BLK',     type=_inputTypeDefault,group='Input Set1',      inline='3',     title='Stk_06')
c1_07= input('C',       type=_inputTypeDefault,group='Input Set1',      inline='4',     title='Stk_07')
c1_08= input('CAT',     type=_inputTypeDefault,group='Input Set1',      inline='4',     title='Stk_08')
c1_09= input('PSA',     type=_inputTypeDefault,group='Input Set1',      inline='5',     title='Stk_09')
c1_10= input('CCI',     type=_inputTypeDefault,group='Input Set1',      inline='5',     title='Stk_10')
c1_11= input('D',       type=_inputTypeDefault,group='Input Set1',      inline='6',     title='Stk_11')
c1_12= input('DE',      type=_inputTypeDefault,group='Input Set1',      inline='6',     title='Stk_12')
c1_13= input('DUK',     type=_inputTypeDefault,group='Input Set1',      inline='7',     title='Stk_13')
c1_14= input('EQIX',    type=_inputTypeDefault,group='Input Set1',      inline='7',     title='Stk_14')
c1_15= input('EXC',     type=_inputTypeDefault,group='Input Set1',      inline='8',     title='Stk_15')
c1_16= input('GE',      type=_inputTypeDefault,group='Input Set1',      inline='8',     title='Stk_16')
c1_17= input('GS',      type=_inputTypeDefault,group='Input Set1',      inline='9',     title='Stk_17')
c1_18= input('DLR',      type=_inputTypeDefault,group='Input Set1',      inline='9',     title='Stk_18')
c1_19= input('HON',     type=_inputTypeDefault,group='Input Set1',      inline='10',    title='Stk_19')
c1_20= input('WELL',     type=_inputTypeDefault,group='Input Set1',      inline='10',    title='Stk_20')
c1_21= input('IBM',     type=_inputTypeDefault,group='Input Set1',      inline='11',    title='Stk_21')
c1_22= input('LMT',     type=_inputTypeDefault,group='Input Set1',      inline='11',    title='Stk_22')
c1_23= input('LOW',     type=_inputTypeDefault,group='Input Set1',      inline='12',    title='Stk_23')
c1_24= input('MCD',     type=_inputTypeDefault,group='Input Set1',      inline='12',    title='Stk_24')
c1_25= input('CLOV',     type=_inputTypeDefault,group='Input Set1',      inline='13',    title='Stk_25')
c1_26= input('MDT',     type=_inputTypeDefault,group='Input Set1',      inline='13',    title='Stk_26')
c1_27= input('MMM',     type=_inputTypeDefault,group='Input Set1',      inline='14',    title='Stk_27')
c1_28= input('SPLK',     type=_inputTypeDefault,group='Input Set1',      inline='14',    title='Stk_28')
c1_29= input('MO',      type=_inputTypeDefault,group='Input Set1',      inline='15',    title='Stk_29')
c1_30= input('MS',      type=_inputTypeDefault,group='Input Set1',      inline='15',    title='Stk_30')
c1_31= input('NEE',     type=_inputTypeDefault,group='Input Set1',      inline='16',    title='Stk_31')
c1_32= input('PLD',     type=_inputTypeDefault,group='Input Set1',      inline='16',    title='Stk_32')
c1_33= input('RTX',     type=_inputTypeDefault,group='Input Set1',      inline='17',    title='Stk_33')
c1_34= input('SO',      type=_inputTypeDefault,group='Input Set1',      inline='17',    title='Stk_34')
c1_35= input('TGT',     type=_inputTypeDefault,group='Input Set1',      inline='18',    title='Stk_35')
c1_36= input('TJX',     type=_inputTypeDefault,group='Input Set1',      inline='18',    title='Stk_36')
c1_37= input('TRV',     type=_inputTypeDefault,group='Input Set1',      inline='19',    title='Stk_37')
c1_38= input('UNP',     type=_inputTypeDefault,group='Input Set1',      inline='19',    title='Stk_38')
c1_39= input('UPS',     type=_inputTypeDefault,group='Input Set1',      inline='20',    title='Stk_39')
c1_40= input('WFC',     type=_inputTypeDefault,group='Input Set1',      inline='20',    title='Stk_40')

c2_01= input('ABNB',    type=_inputTypeDefault,group='Input Set2',      inline='1',     title='Stk_01')
c2_02= input('ALLY',    type=_inputTypeDefault,group='Input Set2',      inline='1',     title='Stk_02')
c2_03= input('AMC',     type=_inputTypeDefault,group='Input Set2',      inline='2',     title='Stk_03')
c2_04= input('BB',      type=_inputTypeDefault,group='Input Set2',      inline='2',     title='Stk_04')
c2_05= input('CHWY',    type=_inputTypeDefault,group='Input Set2',      inline='3',     title='Stk_05')
c2_06= input('CRWD',    type=_inputTypeDefault,group='Input Set2',      inline='3',     title='Stk_06')
c2_07= input('DASH',    type=_inputTypeDefault,group='Input Set2',      inline='4',     title='Stk_07')
c2_08= input('DDOG',    type=_inputTypeDefault,group='Input Set2',      inline='4',     title='Stk_08')
c2_09= input('DLR',     type=_inputTypeDefault,group='Input Set2',      inline='5',     title='Stk_09')
c2_10= input('ET',      type=_inputTypeDefault,group='Input Set2',      inline='5',     title='Stk_10')
c2_11= input('ETSY',    type=_inputTypeDefault,group='Input Set2',      inline='6',     title='Stk_11')
c2_12= input('FSLY',    type=_inputTypeDefault,group='Input Set2',      inline='6',     title='Stk_12')
c2_13= input('GME',     type=_inputTypeDefault,group='Input Set2',      inline='7',     title='Stk_13')
c2_14= input('HUBS',    type=_inputTypeDefault,group='Input Set2',      inline='7',     title='Stk_14')
c2_15= input('LULU',    type=_inputTypeDefault,group='Input Set2',      inline='8',     title='Stk_15')
c2_16= input('LYFT',    type=_inputTypeDefault,group='Input Set2',      inline='8',     title='Stk_16')
c2_17= input('MDB',     type=_inputTypeDefault,group='Input Set2',      inline='9',     title='Stk_17')
c2_18= input('MRVL',    type=_inputTypeDefault,group='Input Set2',      inline='9',     title='Stk_18')
c2_19= input('MTCH',    type=_inputTypeDefault,group='Input Set2',      inline='10',    title='Stk_19')
c2_20= input('NET',     type=_inputTypeDefault,group='Input Set2',      inline='10',    title='Stk_20')
c2_21= input('OKTA',    type=_inputTypeDefault,group='Input Set2',      inline='11',    title='Stk_21')
c2_22= input('PANW',    type=_inputTypeDefault,group='Input Set2',      inline='11',    title='Stk_22')
c2_23= input('BYND',    type=_inputTypeDefault,group='Input Set2',      inline='12',    title='Stk_23')
c2_24= input('PINS',    type=_inputTypeDefault,group='Input Set2',      inline='12',    title='Stk_24')
c2_25= input('PTON',    type=_inputTypeDefault,group='Input Set2',      inline='13',    title='Stk_25')
c2_26= input('RBLX',    type=_inputTypeDefault,group='Input Set2',      inline='13',    title='Stk_26')
c2_27= input('PENN',    type=_inputTypeDefault,group='Input Set2',      inline='14',    title='Stk_27')
c2_28= input('SNAP',    type=_inputTypeDefault,group='Input Set2',      inline='14',    title='Stk_28')
c2_29= input('SNOW',    type=_inputTypeDefault,group='Input Set2',      inline='15',    title='Stk_29')
c2_30= input('TSM',     type=_inputTypeDefault,group='Input Set2',      inline='15',    title='Stk_30')
c2_31= input('TTD',     type=_inputTypeDefault,group='Input Set2',      inline='16',    title='Stk_31')
c2_32= input('UBER',    type=_inputTypeDefault,group='Input Set2',      inline='16',    title='Stk_32')
c2_33= input('UPST',    type=_inputTypeDefault,group='Input Set2',      inline='17',    title='Stk_33')
c2_34= input('WDAY',    type=_inputTypeDefault,group='Input Set2',      inline='17',    title='Stk_34')
c2_35= input('WDAY',    type=_inputTypeDefault,group='Input Set2',      inline='18',    title='Stk_35')
c2_36= input('WELL',    type=_inputTypeDefault,group='Input Set2',      inline='18',    title='Stk_36')
c2_37= input('WISH',    type=_inputTypeDefault,group='Input Set2',      inline='19',    title='Stk_37')
c2_38= input('WMB',     type=_inputTypeDefault,group='Input Set2',      inline='19',    title='Stk_38')
c2_39= input('WORK',    type=_inputTypeDefault,group='Input Set2',      inline='20',    title='Stk_39')
c2_40= input('ZS',      type=_inputTypeDefault,group='Input Set2',      inline='20',    title='Stk_40')

// Security conditional based on input flags
s01=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_01, iff(_activeDataSet=='2) Market Cap Top 40', mcap_01,iff(_activeDataSet=='3) ARKK Top 40', arkk_01,iff(_activeDataSet=='4) International Top 40', intl_01, iff(_activeDataSet=='5) Custom Input Set1', c1_01, iff(_activeDataSet=='6) Custom Input Set2', c2_01, main_01))))))
s02=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_02, iff(_activeDataSet=='2) Market Cap Top 40', mcap_02,iff(_activeDataSet=='3) ARKK Top 40', arkk_02,iff(_activeDataSet=='4) International Top 40', intl_02, iff(_activeDataSet=='5) Custom Input Set1', c1_02, iff(_activeDataSet=='6) Custom Input Set2', c2_02, main_02))))))
s03=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_03, iff(_activeDataSet=='2) Market Cap Top 40', mcap_03,iff(_activeDataSet=='3) ARKK Top 40', arkk_03,iff(_activeDataSet=='4) International Top 40', intl_03, iff(_activeDataSet=='5) Custom Input Set1', c1_03, iff(_activeDataSet=='6) Custom Input Set2', c2_03, main_03))))))
s04=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_04, iff(_activeDataSet=='2) Market Cap Top 40', mcap_04,iff(_activeDataSet=='3) ARKK Top 40', arkk_04,iff(_activeDataSet=='4) International Top 40', intl_04, iff(_activeDataSet=='5) Custom Input Set1', c1_04, iff(_activeDataSet=='6) Custom Input Set2', c2_04, main_03))))))
s05=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_05, iff(_activeDataSet=='2) Market Cap Top 40', mcap_05,iff(_activeDataSet=='3) ARKK Top 40', arkk_05,iff(_activeDataSet=='4) International Top 40', intl_05, iff(_activeDataSet=='5) Custom Input Set1', c1_05, iff(_activeDataSet=='6) Custom Input Set2', c2_05, main_04))))))
s06=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_06, iff(_activeDataSet=='2) Market Cap Top 40', mcap_06,iff(_activeDataSet=='3) ARKK Top 40', arkk_06,iff(_activeDataSet=='4) International Top 40', intl_06, iff(_activeDataSet=='5) Custom Input Set1', c1_06, iff(_activeDataSet=='6) Custom Input Set2', c2_06, main_04))))))
s07=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_07, iff(_activeDataSet=='2) Market Cap Top 40', mcap_07,iff(_activeDataSet=='3) ARKK Top 40', arkk_07,iff(_activeDataSet=='4) International Top 40', intl_07, iff(_activeDataSet=='5) Custom Input Set1', c1_07, iff(_activeDataSet=='6) Custom Input Set2', c2_07, main_05))))))
s08=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_08, iff(_activeDataSet=='2) Market Cap Top 40', mcap_08,iff(_activeDataSet=='3) ARKK Top 40', arkk_08,iff(_activeDataSet=='4) International Top 40', intl_08, iff(_activeDataSet=='5) Custom Input Set1', c1_08, iff(_activeDataSet=='6) Custom Input Set2', c2_08, main_06))))))
s09=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_09, iff(_activeDataSet=='2) Market Cap Top 40', mcap_09,iff(_activeDataSet=='3) ARKK Top 40', arkk_09,iff(_activeDataSet=='4) International Top 40', intl_09, iff(_activeDataSet=='5) Custom Input Set1', c1_09, iff(_activeDataSet=='6) Custom Input Set2', c2_09, main_07))))))
s10=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_10, iff(_activeDataSet=='2) Market Cap Top 40', mcap_10,iff(_activeDataSet=='3) ARKK Top 40', arkk_10,iff(_activeDataSet=='4) International Top 40', intl_10, iff(_activeDataSet=='5) Custom Input Set1', c1_10, iff(_activeDataSet=='6) Custom Input Set2', c2_10, main_10))))))
s11=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_11, iff(_activeDataSet=='2) Market Cap Top 40', mcap_11,iff(_activeDataSet=='3) ARKK Top 40', arkk_11,iff(_activeDataSet=='4) International Top 40', intl_11, iff(_activeDataSet=='5) Custom Input Set1', c1_11, iff(_activeDataSet=='6) Custom Input Set2', c2_11, main_11))))))
s12=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_12, iff(_activeDataSet=='2) Market Cap Top 40', mcap_12,iff(_activeDataSet=='3) ARKK Top 40', arkk_12,iff(_activeDataSet=='4) International Top 40', intl_12, iff(_activeDataSet=='5) Custom Input Set1', c1_12, iff(_activeDataSet=='6) Custom Input Set2', c2_12, main_12))))))
s13=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_13, iff(_activeDataSet=='2) Market Cap Top 40', mcap_13,iff(_activeDataSet=='3) ARKK Top 40', arkk_13,iff(_activeDataSet=='4) International Top 40', intl_13, iff(_activeDataSet=='5) Custom Input Set1', c1_13, iff(_activeDataSet=='6) Custom Input Set2', c2_13, main_13))))))
s14=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_14, iff(_activeDataSet=='2) Market Cap Top 40', mcap_14,iff(_activeDataSet=='3) ARKK Top 40', arkk_14,iff(_activeDataSet=='4) International Top 40', intl_14, iff(_activeDataSet=='5) Custom Input Set1', c1_14, iff(_activeDataSet=='6) Custom Input Set2', c2_14, main_13))))))
s15=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_15, iff(_activeDataSet=='2) Market Cap Top 40', mcap_15,iff(_activeDataSet=='3) ARKK Top 40', arkk_15,iff(_activeDataSet=='4) International Top 40', intl_15, iff(_activeDataSet=='5) Custom Input Set1', c1_15, iff(_activeDataSet=='6) Custom Input Set2', c2_15, main_14))))))
s16=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_16, iff(_activeDataSet=='2) Market Cap Top 40', mcap_16,iff(_activeDataSet=='3) ARKK Top 40', arkk_16,iff(_activeDataSet=='4) International Top 40', intl_16, iff(_activeDataSet=='5) Custom Input Set1', c1_16, iff(_activeDataSet=='6) Custom Input Set2', c2_16, main_14))))))
s17=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_17, iff(_activeDataSet=='2) Market Cap Top 40', mcap_17,iff(_activeDataSet=='3) ARKK Top 40', arkk_17,iff(_activeDataSet=='4) International Top 40', intl_17, iff(_activeDataSet=='5) Custom Input Set1', c1_17, iff(_activeDataSet=='6) Custom Input Set2', c2_17, main_15))))))
s18=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_18, iff(_activeDataSet=='2) Market Cap Top 40', mcap_18,iff(_activeDataSet=='3) ARKK Top 40', arkk_18,iff(_activeDataSet=='4) International Top 40', intl_18, iff(_activeDataSet=='5) Custom Input Set1', c1_18, iff(_activeDataSet=='6) Custom Input Set2', c2_18, main_16))))))
s19=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_19, iff(_activeDataSet=='2) Market Cap Top 40', mcap_19,iff(_activeDataSet=='3) ARKK Top 40', arkk_19,iff(_activeDataSet=='4) International Top 40', intl_19, iff(_activeDataSet=='5) Custom Input Set1', c1_19, iff(_activeDataSet=='6) Custom Input Set2', c2_19, main_17))))))
s20=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_20, iff(_activeDataSet=='2) Market Cap Top 40', mcap_20,iff(_activeDataSet=='3) ARKK Top 40', arkk_20,iff(_activeDataSet=='4) International Top 40', intl_20, iff(_activeDataSet=='5) Custom Input Set1', c1_20, iff(_activeDataSet=='6) Custom Input Set2', c2_20, main_20))))))
s21=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_21, iff(_activeDataSet=='2) Market Cap Top 40', mcap_21,iff(_activeDataSet=='3) ARKK Top 40', arkk_21,iff(_activeDataSet=='4) International Top 40', intl_21, iff(_activeDataSet=='5) Custom Input Set1', c1_21, iff(_activeDataSet=='6) Custom Input Set2', c2_21, main_21))))))
s22=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_22, iff(_activeDataSet=='2) Market Cap Top 40', mcap_22,iff(_activeDataSet=='3) ARKK Top 40', arkk_22,iff(_activeDataSet=='4) International Top 40', intl_22, iff(_activeDataSet=='5) Custom Input Set1', c1_22, iff(_activeDataSet=='6) Custom Input Set2', c2_22, main_22))))))
s23=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_23, iff(_activeDataSet=='2) Market Cap Top 40', mcap_23,iff(_activeDataSet=='3) ARKK Top 40', arkk_23,iff(_activeDataSet=='4) International Top 40', intl_23, iff(_activeDataSet=='5) Custom Input Set1', c1_23, iff(_activeDataSet=='6) Custom Input Set2', c2_23, main_23))))))
s24=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_24, iff(_activeDataSet=='2) Market Cap Top 40', mcap_24,iff(_activeDataSet=='3) ARKK Top 40', arkk_24,iff(_activeDataSet=='4) International Top 40', intl_24, iff(_activeDataSet=='5) Custom Input Set1', c1_24, iff(_activeDataSet=='6) Custom Input Set2', c2_24, main_23))))))
s25=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_25, iff(_activeDataSet=='2) Market Cap Top 40', mcap_25,iff(_activeDataSet=='3) ARKK Top 40', arkk_25,iff(_activeDataSet=='4) International Top 40', intl_25, iff(_activeDataSet=='5) Custom Input Set1', c1_25, iff(_activeDataSet=='6) Custom Input Set2', c2_25, main_24))))))
s26=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_26, iff(_activeDataSet=='2) Market Cap Top 40', mcap_26,iff(_activeDataSet=='3) ARKK Top 40', arkk_26,iff(_activeDataSet=='4) International Top 40', intl_26, iff(_activeDataSet=='5) Custom Input Set1', c1_26, iff(_activeDataSet=='6) Custom Input Set2', c2_26, main_24))))))
s27=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_27, iff(_activeDataSet=='2) Market Cap Top 40', mcap_27,iff(_activeDataSet=='3) ARKK Top 40', arkk_27,iff(_activeDataSet=='4) International Top 40', intl_27, iff(_activeDataSet=='5) Custom Input Set1', c1_27, iff(_activeDataSet=='6) Custom Input Set2', c2_27, main_25))))))
s28=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_28, iff(_activeDataSet=='2) Market Cap Top 40', mcap_28,iff(_activeDataSet=='3) ARKK Top 40', arkk_28,iff(_activeDataSet=='4) International Top 40', intl_28, iff(_activeDataSet=='5) Custom Input Set1', c1_28, iff(_activeDataSet=='6) Custom Input Set2', c2_28, main_26))))))
s29=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_29, iff(_activeDataSet=='2) Market Cap Top 40', mcap_29,iff(_activeDataSet=='3) ARKK Top 40', arkk_29,iff(_activeDataSet=='4) International Top 40', intl_29, iff(_activeDataSet=='5) Custom Input Set1', c1_29, iff(_activeDataSet=='6) Custom Input Set2', c2_29, main_27))))))
s30=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_30, iff(_activeDataSet=='2) Market Cap Top 40', mcap_30,iff(_activeDataSet=='3) ARKK Top 40', arkk_30,iff(_activeDataSet=='4) International Top 40', intl_30, iff(_activeDataSet=='5) Custom Input Set1', c1_30, iff(_activeDataSet=='6) Custom Input Set2', c2_30, main_30))))))
s31=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_31, iff(_activeDataSet=='2) Market Cap Top 40', mcap_31,iff(_activeDataSet=='3) ARKK Top 40', arkk_31,iff(_activeDataSet=='4) International Top 40', intl_31, iff(_activeDataSet=='5) Custom Input Set1', c1_31, iff(_activeDataSet=='6) Custom Input Set2', c2_31, main_31))))))
s32=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_32, iff(_activeDataSet=='2) Market Cap Top 40', mcap_32,iff(_activeDataSet=='3) ARKK Top 40', arkk_32,iff(_activeDataSet=='4) International Top 40', intl_32, iff(_activeDataSet=='5) Custom Input Set1', c1_32, iff(_activeDataSet=='6) Custom Input Set2', c2_32, main_32))))))
s33=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_33, iff(_activeDataSet=='2) Market Cap Top 40', mcap_33,iff(_activeDataSet=='3) ARKK Top 40', arkk_33,iff(_activeDataSet=='4) International Top 40', intl_33, iff(_activeDataSet=='5) Custom Input Set1', c1_33, iff(_activeDataSet=='6) Custom Input Set2', c2_33, main_33))))))
s34=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_34, iff(_activeDataSet=='2) Market Cap Top 40', mcap_34,iff(_activeDataSet=='3) ARKK Top 40', arkk_34,iff(_activeDataSet=='4) International Top 40', intl_34, iff(_activeDataSet=='5) Custom Input Set1', c1_34, iff(_activeDataSet=='6) Custom Input Set2', c2_34, main_33))))))
s35=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_35, iff(_activeDataSet=='2) Market Cap Top 40', mcap_35,iff(_activeDataSet=='3) ARKK Top 40', arkk_35,iff(_activeDataSet=='4) International Top 40', intl_35, iff(_activeDataSet=='5) Custom Input Set1', c1_35, iff(_activeDataSet=='6) Custom Input Set2', c2_35, main_34))))))
s36=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_36, iff(_activeDataSet=='2) Market Cap Top 40', mcap_36,iff(_activeDataSet=='3) ARKK Top 40', arkk_36,iff(_activeDataSet=='4) International Top 40', intl_36, iff(_activeDataSet=='5) Custom Input Set1', c1_36, iff(_activeDataSet=='6) Custom Input Set2', c2_36, main_34))))))
s37=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_37, iff(_activeDataSet=='2) Market Cap Top 40', mcap_37,iff(_activeDataSet=='3) ARKK Top 40', arkk_37,iff(_activeDataSet=='4) International Top 40', intl_37, iff(_activeDataSet=='5) Custom Input Set1', c1_37, iff(_activeDataSet=='6) Custom Input Set2', c2_37, main_35))))))
s38=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_38, iff(_activeDataSet=='2) Market Cap Top 40', mcap_38,iff(_activeDataSet=='3) ARKK Top 40', arkk_38,iff(_activeDataSet=='4) International Top 40', intl_38, iff(_activeDataSet=='5) Custom Input Set1', c1_38, iff(_activeDataSet=='6) Custom Input Set2', c2_38, main_36))))))
s39=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_39, iff(_activeDataSet=='2) Market Cap Top 40', mcap_39,iff(_activeDataSet=='3) ARKK Top 40', arkk_39,iff(_activeDataSet=='4) International Top 40', intl_39, iff(_activeDataSet=='5) Custom Input Set1', c1_39, iff(_activeDataSet=='6) Custom Input Set2', c2_39, main_37))))))
s40=iff(_activeDataSet == '1) Main Sector/ETF/Future Top 40', main_40, iff(_activeDataSet=='2) Market Cap Top 40', mcap_40,iff(_activeDataSet=='3) ARKK Top 40', arkk_40,iff(_activeDataSet=='4) International Top 40', intl_40, iff(_activeDataSet=='5) Custom Input Set1', c1_40, iff(_activeDataSet=='6) Custom Input Set2', c2_40, main_40))))))

// FUNCTIONS
getActionalbeWickHeight(wickPercentage) =>
    (high[0] - low[0])*wickPercentage

getShooterTop   = high[0] - getActionalbeWickHeight(_actionWickPercentage)
getHammerBottom = low[0] + getActionalbeWickHeight(_actionWickPercentage)

// ACTIONALBE SIGNAL LOOKUPS

isInside() =>
    high[0] <= high[1] and low[0] >= low[1]

isShooterLogic() =>
    open[0] < getShooterTop and close[0] < getShooterTop

isHammerLogic() =>
    open[0] > getHammerBottom and close[0] > getHammerBottom

// OTHER CANDLE LOOKUPS
isTwoDownLogic() =>
    low[0] < low[1] and not (high[0] > high[1])

isTwoUpLogic() =>
    high[0] > high[1] and not (low[0] < low[1])

isOutsideLogic() =>
    high[0] > high[1] and low[0] < low[1]

isGreen() =>
    open[0] < close[0]

isRed()=>
    open[0] >= close[0]

// Series/Security logic check - prevents having to have 100 variables
isOutside() =>
   iff(isOutsideLogic() and isGreen(), _isGreenCandleResult, iff(isOutsideLogic() and isRed(), _isRedCandleResult, -1))

isHammer() =>
   iff(isHammerLogic() and isGreen(), _isGreenCandleResult, iff(isHammerLogic() and isRed(), _isRedCandleResult, -1))

isShooter() =>
   iff(isShooterLogic() and isGreen(), _isGreenCandleResult, iff(isShooterLogic() and isRed(), _isRedCandleResult, -1))

isTwoUp() =>
   iff(isTwoUpLogic() and isGreen(), _isGreenCandleResult, iff(isTwoUpLogic() and isRed(), _isRedCandleResult, -1))

isTwoDown() =>
   iff(isTwoDownLogic() and isGreen(), _isGreenCandleResult, iff(isTwoDownLogic() and isRed(), _isRedCandleResult, -1))


//LABELS and LABEL TEXT
createLabelText(text, isCandleTest, expectedResult, security) =>
    iff(isCandleTest == expectedResult, text + security + _newLineText, text)

createFinalFormattedLabelText(typeText, typeGreenText, typeRedText) =>
    _labelHeaderText + typeText + _labelGreenText + typeGreenText + "\n" + _labelRedText + typeRedText

// SECURITY GETS (getting data for all securities with TUPLES)
[inside01, shooter01, hammer01, twoDown01, twoUp01, outside01] = security(s01, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside02, shooter02, hammer02, twoDown02, twoUp02, outside02] = security(s02, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside03, shooter03, hammer03, twoDown03, twoUp03, outside03] = security(s03, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside04, shooter04, hammer04, twoDown04, twoUp04, outside04] = security(s04, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside05, shooter05, hammer05, twoDown05, twoUp05, outside05] = security(s05, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside06, shooter06, hammer06, twoDown06, twoUp06, outside06] = security(s06, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside07, shooter07, hammer07, twoDown07, twoUp07, outside07] = security(s07, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside08, shooter08, hammer08, twoDown08, twoUp08, outside08] = security(s08, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside09, shooter09, hammer09, twoDown09, twoUp09, outside09] = security(s09, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside10, shooter10, hammer10, twoDown10, twoUp10, outside10] = security(s10, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside11, shooter11, hammer11, twoDown11, twoUp11, outside11] = security(s11, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside12, shooter12, hammer12, twoDown12, twoUp12, outside12] = security(s12, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside13, shooter13, hammer13, twoDown13, twoUp13, outside13] = security(s13, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside14, shooter14, hammer14, twoDown14, twoUp14, outside14] = security(s14, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside15, shooter15, hammer15, twoDown15, twoUp15, outside15] = security(s15, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside16, shooter16, hammer16, twoDown16, twoUp16, outside16] = security(s16, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside17, shooter17, hammer17, twoDown17, twoUp17, outside17] = security(s17, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside18, shooter18, hammer18, twoDown18, twoUp18, outside18] = security(s18, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside19, shooter19, hammer19, twoDown19, twoUp19, outside19] = security(s19, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside20, shooter20, hammer20, twoDown20, twoUp20, outside20] = security(s20, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside21, shooter21, hammer21, twoDown21, twoUp21, outside21] = security(s21, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside22, shooter22, hammer22, twoDown22, twoUp22, outside22] = security(s22, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside23, shooter23, hammer23, twoDown23, twoUp23, outside23] = security(s23, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside24, shooter24, hammer24, twoDown24, twoUp24, outside24] = security(s24, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside25, shooter25, hammer25, twoDown25, twoUp25, outside25] = security(s25, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside26, shooter26, hammer26, twoDown26, twoUp26, outside26] = security(s26, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside27, shooter27, hammer27, twoDown27, twoUp27, outside27] = security(s27, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside28, shooter28, hammer28, twoDown28, twoUp28, outside28] = security(s28, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside29, shooter29, hammer29, twoDown29, twoUp29, outside29] = security(s29, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside30, shooter30, hammer30, twoDown30, twoUp30, outside30] = security(s30, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside31, shooter31, hammer31, twoDown31, twoUp31, outside31] = security(s31, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside32, shooter32, hammer32, twoDown32, twoUp32, outside32] = security(s32, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside33, shooter33, hammer33, twoDown33, twoUp33, outside33] = security(s33, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside34, shooter34, hammer34, twoDown34, twoUp34, outside34] = security(s34, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside35, shooter35, hammer35, twoDown35, twoUp35, outside35] = security(s35, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside36, shooter36, hammer36, twoDown36, twoUp36, outside36] = security(s36, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside37, shooter37, hammer37, twoDown37, twoUp37, outside37] = security(s37, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside38, shooter38, hammer38, twoDown38, twoUp38, outside38] = security(s38, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside39, shooter39, hammer39, twoDown39, twoUp39, outside39] = security(s39, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])
[inside40, shooter40, hammer40, twoDown40, twoUp40, outside40] = security(s40, _securityTimeFrame, [isInside(), isShooter(), isHammer(), isTwoDown(), isTwoUp(), isOutside()])


// LABEL BUILDING
// really wish I could do this in a function, tried, but got lazy
insideText := inside01 != 0  ? insideText + s01 +  _newLineText  : insideText
insideText := inside02 != 0  ? insideText + s02 +  _newLineText  : insideText
insideText := inside03 != 0  ? insideText + s03 +  _newLineText  : insideText
insideText := inside04 != 0  ? insideText + s04 +  _newLineText  : insideText
insideText := inside05 != 0  ? insideText + s05 +  _newLineText  : insideText
insideText := inside06 != 0  ? insideText + s06 +  _newLineText  : insideText
insideText := inside07 != 0  ? insideText + s07 +  _newLineText  : insideText
insideText := inside08 != 0  ? insideText + s08 +  _newLineText  : insideText
insideText := inside09 != 0  ? insideText + s09 +  _newLineText  : insideText
insideText := inside10 != 0  ? insideText + s10 +  _newLineText  : insideText
insideText := inside11 != 0  ? insideText + s11 +  _newLineText  : insideText
insideText := inside12 != 0  ? insideText + s12 +  _newLineText  : insideText
insideText := inside13 != 0  ? insideText + s13 +  _newLineText  : insideText
insideText := inside14 != 0  ? insideText + s14 +  _newLineText  : insideText
insideText := inside15 != 0  ? insideText + s15 +  _newLineText  : insideText
insideText := inside16 != 0  ? insideText + s16 +  _newLineText  : insideText
insideText := inside17 != 0  ? insideText + s17 +  _newLineText  : insideText
insideText := inside18 != 0  ? insideText + s18 +  _newLineText  : insideText
insideText := inside19 != 0  ? insideText + s19 +  _newLineText  : insideText
insideText := inside20 != 0  ? insideText + s20 +  _newLineText  : insideText
insideText := inside21 != 0  ? insideText + s21 +  _newLineText  : insideText
insideText := inside22 != 0  ? insideText + s22 +  _newLineText  : insideText
insideText := inside23 != 0  ? insideText + s23 +  _newLineText  : insideText
insideText := inside24 != 0  ? insideText + s24 +  _newLineText  : insideText
insideText := inside25 != 0  ? insideText + s25 +  _newLineText  : insideText
insideText := inside26 != 0  ? insideText + s26 +  _newLineText  : insideText
insideText := inside27 != 0  ? insideText + s27 +  _newLineText  : insideText
insideText := inside28 != 0  ? insideText + s28 +  _newLineText  : insideText
insideText := inside29 != 0  ? insideText + s29 +  _newLineText  : insideText
insideText := inside30 != 0  ? insideText + s30 +  _newLineText  : insideText
insideText := inside31 != 0  ? insideText + s31 +  _newLineText  : insideText
insideText := inside32 != 0  ? insideText + s32 +  _newLineText  : insideText
insideText := inside33 != 0  ? insideText + s33 +  _newLineText  : insideText
insideText := inside34 != 0  ? insideText + s34 +  _newLineText  : insideText
insideText := inside35 != 0  ? insideText + s35 +  _newLineText  : insideText
insideText := inside36 != 0  ? insideText + s36 +  _newLineText  : insideText
insideText := inside37 != 0  ? insideText + s37 +  _newLineText  : insideText
insideText := inside38 != 0  ? insideText + s38 +  _newLineText  : insideText
insideText := inside39 != 0  ? insideText + s39 +  _newLineText  : insideText
insideText := inside40 != 0  ? insideText + s40 +  _newLineText  : insideText

shooterGreenText := createLabelText(shooterGreenText, shooter01, _isGreenCandleResult, s01)
shooterGreenText := createLabelText(shooterGreenText, shooter02, _isGreenCandleResult, s02)
shooterGreenText := createLabelText(shooterGreenText, shooter03, _isGreenCandleResult, s03)
shooterGreenText := createLabelText(shooterGreenText, shooter04, _isGreenCandleResult, s04)
shooterGreenText := createLabelText(shooterGreenText, shooter05, _isGreenCandleResult, s05)
shooterGreenText := createLabelText(shooterGreenText, shooter06, _isGreenCandleResult, s06)
shooterGreenText := createLabelText(shooterGreenText, shooter07, _isGreenCandleResult, s07)
shooterGreenText := createLabelText(shooterGreenText, shooter08, _isGreenCandleResult, s08)
shooterGreenText := createLabelText(shooterGreenText, shooter09, _isGreenCandleResult, s09)
shooterGreenText := createLabelText(shooterGreenText, shooter10, _isGreenCandleResult, s10)
shooterGreenText := createLabelText(shooterGreenText, shooter11, _isGreenCandleResult, s11)
shooterGreenText := createLabelText(shooterGreenText, shooter12, _isGreenCandleResult, s12)
shooterGreenText := createLabelText(shooterGreenText, shooter13, _isGreenCandleResult, s13)
shooterGreenText := createLabelText(shooterGreenText, shooter14, _isGreenCandleResult, s14)
shooterGreenText := createLabelText(shooterGreenText, shooter15, _isGreenCandleResult, s15)
shooterGreenText := createLabelText(shooterGreenText, shooter16, _isGreenCandleResult, s16)
shooterGreenText := createLabelText(shooterGreenText, shooter17, _isGreenCandleResult, s17)
shooterGreenText := createLabelText(shooterGreenText, shooter18, _isGreenCandleResult, s18)
shooterGreenText := createLabelText(shooterGreenText, shooter19, _isGreenCandleResult, s19)
shooterGreenText := createLabelText(shooterGreenText, shooter20, _isGreenCandleResult, s20)
shooterGreenText := createLabelText(shooterGreenText, shooter21, _isGreenCandleResult, s21)
shooterGreenText := createLabelText(shooterGreenText, shooter22, _isGreenCandleResult, s22)
shooterGreenText := createLabelText(shooterGreenText, shooter23, _isGreenCandleResult, s23)
shooterGreenText := createLabelText(shooterGreenText, shooter24, _isGreenCandleResult, s24)
shooterGreenText := createLabelText(shooterGreenText, shooter25, _isGreenCandleResult, s25)
shooterGreenText := createLabelText(shooterGreenText, shooter26, _isGreenCandleResult, s26)
shooterGreenText := createLabelText(shooterGreenText, shooter27, _isGreenCandleResult, s27)
shooterGreenText := createLabelText(shooterGreenText, shooter28, _isGreenCandleResult, s28)
shooterGreenText := createLabelText(shooterGreenText, shooter29, _isGreenCandleResult, s29)
shooterGreenText := createLabelText(shooterGreenText, shooter30, _isGreenCandleResult, s30)
shooterGreenText := createLabelText(shooterGreenText, shooter31, _isGreenCandleResult, s31)
shooterGreenText := createLabelText(shooterGreenText, shooter32, _isGreenCandleResult, s32)
shooterGreenText := createLabelText(shooterGreenText, shooter33, _isGreenCandleResult, s33)
shooterGreenText := createLabelText(shooterGreenText, shooter34, _isGreenCandleResult, s34)
shooterGreenText := createLabelText(shooterGreenText, shooter35, _isGreenCandleResult, s35)
shooterGreenText := createLabelText(shooterGreenText, shooter36, _isGreenCandleResult, s36)
shooterGreenText := createLabelText(shooterGreenText, shooter37, _isGreenCandleResult, s37)
shooterGreenText := createLabelText(shooterGreenText, shooter38, _isGreenCandleResult, s38)
shooterGreenText := createLabelText(shooterGreenText, shooter39, _isGreenCandleResult, s39)
shooterGreenText := createLabelText(shooterGreenText, shooter40, _isGreenCandleResult, s40)

shooterRedText := createLabelText(shooterRedText, shooter01, _isRedCandleResult, s01)
shooterRedText := createLabelText(shooterRedText, shooter02, _isRedCandleResult, s02)
shooterRedText := createLabelText(shooterRedText, shooter03, _isRedCandleResult, s03)
shooterRedText := createLabelText(shooterRedText, shooter04, _isRedCandleResult, s04)
shooterRedText := createLabelText(shooterRedText, shooter05, _isRedCandleResult, s05)
shooterRedText := createLabelText(shooterRedText, shooter06, _isRedCandleResult, s06)
shooterRedText := createLabelText(shooterRedText, shooter07, _isRedCandleResult, s07)
shooterRedText := createLabelText(shooterRedText, shooter08, _isRedCandleResult, s08)
shooterRedText := createLabelText(shooterRedText, shooter09, _isRedCandleResult, s09)
shooterRedText := createLabelText(shooterRedText, shooter10, _isRedCandleResult, s10)
shooterRedText := createLabelText(shooterRedText, shooter11, _isRedCandleResult, s11)
shooterRedText := createLabelText(shooterRedText, shooter12, _isRedCandleResult, s12)
shooterRedText := createLabelText(shooterRedText, shooter13, _isRedCandleResult, s13)
shooterRedText := createLabelText(shooterRedText, shooter14, _isRedCandleResult, s14)
shooterRedText := createLabelText(shooterRedText, shooter15, _isRedCandleResult, s15)
shooterRedText := createLabelText(shooterRedText, shooter16, _isRedCandleResult, s16)
shooterRedText := createLabelText(shooterRedText, shooter17, _isRedCandleResult, s17)
shooterRedText := createLabelText(shooterRedText, shooter18, _isRedCandleResult, s18)
shooterRedText := createLabelText(shooterRedText, shooter19, _isRedCandleResult, s19)
shooterRedText := createLabelText(shooterRedText, shooter20, _isRedCandleResult, s20)
shooterRedText := createLabelText(shooterRedText, shooter21, _isRedCandleResult, s21)
shooterRedText := createLabelText(shooterRedText, shooter22, _isRedCandleResult, s22)
shooterRedText := createLabelText(shooterRedText, shooter23, _isRedCandleResult, s23)
shooterRedText := createLabelText(shooterRedText, shooter24, _isRedCandleResult, s24)
shooterRedText := createLabelText(shooterRedText, shooter25, _isRedCandleResult, s25)
shooterRedText := createLabelText(shooterRedText, shooter26, _isRedCandleResult, s26)
shooterRedText := createLabelText(shooterRedText, shooter27, _isRedCandleResult, s27)
shooterRedText := createLabelText(shooterRedText, shooter28, _isRedCandleResult, s28)
shooterRedText := createLabelText(shooterRedText, shooter29, _isRedCandleResult, s29)
shooterRedText := createLabelText(shooterRedText, shooter30, _isRedCandleResult, s30)
shooterRedText := createLabelText(shooterRedText, shooter31, _isRedCandleResult, s31)
shooterRedText := createLabelText(shooterRedText, shooter32, _isRedCandleResult, s32)
shooterRedText := createLabelText(shooterRedText, shooter33, _isRedCandleResult, s33)
shooterRedText := createLabelText(shooterRedText, shooter34, _isRedCandleResult, s34)
shooterRedText := createLabelText(shooterRedText, shooter35, _isRedCandleResult, s35)
shooterRedText := createLabelText(shooterRedText, shooter36, _isRedCandleResult, s36)
shooterRedText := createLabelText(shooterRedText, shooter37, _isRedCandleResult, s37)
shooterRedText := createLabelText(shooterRedText, shooter38, _isRedCandleResult, s38)
shooterRedText := createLabelText(shooterRedText, shooter39, _isRedCandleResult, s39)
shooterRedText := createLabelText(shooterRedText, shooter40, _isRedCandleResult, s40)

hammerGreenText := createLabelText(hammerGreenText, hammer01, _isGreenCandleResult, s01)
hammerGreenText := createLabelText(hammerGreenText, hammer02, _isGreenCandleResult, s02)
hammerGreenText := createLabelText(hammerGreenText, hammer03, _isGreenCandleResult, s03)
hammerGreenText := createLabelText(hammerGreenText, hammer04, _isGreenCandleResult, s04)
hammerGreenText := createLabelText(hammerGreenText, hammer05, _isGreenCandleResult, s05)
hammerGreenText := createLabelText(hammerGreenText, hammer06, _isGreenCandleResult, s06)
hammerGreenText := createLabelText(hammerGreenText, hammer07, _isGreenCandleResult, s07)
hammerGreenText := createLabelText(hammerGreenText, hammer08, _isGreenCandleResult, s08)
hammerGreenText := createLabelText(hammerGreenText, hammer09, _isGreenCandleResult, s09)
hammerGreenText := createLabelText(hammerGreenText, hammer10, _isGreenCandleResult, s10)
hammerGreenText := createLabelText(hammerGreenText, hammer11, _isGreenCandleResult, s11)
hammerGreenText := createLabelText(hammerGreenText, hammer12, _isGreenCandleResult, s12)
hammerGreenText := createLabelText(hammerGreenText, hammer13, _isGreenCandleResult, s13)
hammerGreenText := createLabelText(hammerGreenText, hammer14, _isGreenCandleResult, s14)
hammerGreenText := createLabelText(hammerGreenText, hammer15, _isGreenCandleResult, s15)
hammerGreenText := createLabelText(hammerGreenText, hammer16, _isGreenCandleResult, s16)
hammerGreenText := createLabelText(hammerGreenText, hammer17, _isGreenCandleResult, s17)
hammerGreenText := createLabelText(hammerGreenText, hammer18, _isGreenCandleResult, s18)
hammerGreenText := createLabelText(hammerGreenText, hammer19, _isGreenCandleResult, s19)
hammerGreenText := createLabelText(hammerGreenText, hammer20, _isGreenCandleResult, s20)
hammerGreenText := createLabelText(hammerGreenText, hammer21, _isGreenCandleResult, s21)
hammerGreenText := createLabelText(hammerGreenText, hammer22, _isGreenCandleResult, s22)
hammerGreenText := createLabelText(hammerGreenText, hammer23, _isGreenCandleResult, s23)
hammerGreenText := createLabelText(hammerGreenText, hammer24, _isGreenCandleResult, s24)
hammerGreenText := createLabelText(hammerGreenText, hammer25, _isGreenCandleResult, s25)
hammerGreenText := createLabelText(hammerGreenText, hammer26, _isGreenCandleResult, s26)
hammerGreenText := createLabelText(hammerGreenText, hammer27, _isGreenCandleResult, s27)
hammerGreenText := createLabelText(hammerGreenText, hammer28, _isGreenCandleResult, s28)
hammerGreenText := createLabelText(hammerGreenText, hammer29, _isGreenCandleResult, s29)
hammerGreenText := createLabelText(hammerGreenText, hammer30, _isGreenCandleResult, s30)
hammerGreenText := createLabelText(hammerGreenText, hammer31, _isGreenCandleResult, s31)
hammerGreenText := createLabelText(hammerGreenText, hammer32, _isGreenCandleResult, s32)
hammerGreenText := createLabelText(hammerGreenText, hammer33, _isGreenCandleResult, s33)
hammerGreenText := createLabelText(hammerGreenText, hammer34, _isGreenCandleResult, s34)
hammerGreenText := createLabelText(hammerGreenText, hammer35, _isGreenCandleResult, s35)
hammerGreenText := createLabelText(hammerGreenText, hammer36, _isGreenCandleResult, s36)
hammerGreenText := createLabelText(hammerGreenText, hammer37, _isGreenCandleResult, s37)
hammerGreenText := createLabelText(hammerGreenText, hammer38, _isGreenCandleResult, s38)
hammerGreenText := createLabelText(hammerGreenText, hammer39, _isGreenCandleResult, s39)
hammerGreenText := createLabelText(hammerGreenText, hammer40, _isGreenCandleResult, s40)

hammerRedText := createLabelText(hammerRedText, hammer01, _isRedCandleResult, s01)
hammerRedText := createLabelText(hammerRedText, hammer02, _isRedCandleResult, s02)
hammerRedText := createLabelText(hammerRedText, hammer03, _isRedCandleResult, s03)
hammerRedText := createLabelText(hammerRedText, hammer04, _isRedCandleResult, s04)
hammerRedText := createLabelText(hammerRedText, hammer05, _isRedCandleResult, s05)
hammerRedText := createLabelText(hammerRedText, hammer06, _isRedCandleResult, s06)
hammerRedText := createLabelText(hammerRedText, hammer07, _isRedCandleResult, s07)
hammerRedText := createLabelText(hammerRedText, hammer08, _isRedCandleResult, s08)
hammerRedText := createLabelText(hammerRedText, hammer09, _isRedCandleResult, s09)
hammerRedText := createLabelText(hammerRedText, hammer10, _isRedCandleResult, s10)
hammerRedText := createLabelText(hammerRedText, hammer11, _isRedCandleResult, s11)
hammerRedText := createLabelText(hammerRedText, hammer12, _isRedCandleResult, s12)
hammerRedText := createLabelText(hammerRedText, hammer13, _isRedCandleResult, s13)
hammerRedText := createLabelText(hammerRedText, hammer14, _isRedCandleResult, s14)
hammerRedText := createLabelText(hammerRedText, hammer15, _isRedCandleResult, s15)
hammerRedText := createLabelText(hammerRedText, hammer16, _isRedCandleResult, s16)
hammerRedText := createLabelText(hammerRedText, hammer17, _isRedCandleResult, s17)
hammerRedText := createLabelText(hammerRedText, hammer18, _isRedCandleResult, s18)
hammerRedText := createLabelText(hammerRedText, hammer19, _isRedCandleResult, s19)
hammerRedText := createLabelText(hammerRedText, hammer20, _isRedCandleResult, s20)
hammerRedText := createLabelText(hammerRedText, hammer21, _isRedCandleResult, s21)
hammerRedText := createLabelText(hammerRedText, hammer22, _isRedCandleResult, s22)
hammerRedText := createLabelText(hammerRedText, hammer23, _isRedCandleResult, s23)
hammerRedText := createLabelText(hammerRedText, hammer24, _isRedCandleResult, s24)
hammerRedText := createLabelText(hammerRedText, hammer25, _isRedCandleResult, s25)
hammerRedText := createLabelText(hammerRedText, hammer26, _isRedCandleResult, s26)
hammerRedText := createLabelText(hammerRedText, hammer27, _isRedCandleResult, s27)
hammerRedText := createLabelText(hammerRedText, hammer28, _isRedCandleResult, s28)
hammerRedText := createLabelText(hammerRedText, hammer29, _isRedCandleResult, s29)
hammerRedText := createLabelText(hammerRedText, hammer30, _isRedCandleResult, s30)
hammerRedText := createLabelText(hammerRedText, hammer31, _isRedCandleResult, s31)
hammerRedText := createLabelText(hammerRedText, hammer32, _isRedCandleResult, s32)
hammerRedText := createLabelText(hammerRedText, hammer33, _isRedCandleResult, s33)
hammerRedText := createLabelText(hammerRedText, hammer34, _isRedCandleResult, s34)
hammerRedText := createLabelText(hammerRedText, hammer35, _isRedCandleResult, s35)
hammerRedText := createLabelText(hammerRedText, hammer36, _isRedCandleResult, s36)
hammerRedText := createLabelText(hammerRedText, hammer37, _isRedCandleResult, s37)
hammerRedText := createLabelText(hammerRedText, hammer38, _isRedCandleResult, s38)
hammerRedText := createLabelText(hammerRedText, hammer39, _isRedCandleResult, s39)
hammerRedText := createLabelText(hammerRedText, hammer40, _isRedCandleResult, s40)


outsideGreenText := createLabelText(outsideGreenText, outside01, _isGreenCandleResult, s01)
outsideGreenText := createLabelText(outsideGreenText, outside02, _isGreenCandleResult, s02)
outsideGreenText := createLabelText(outsideGreenText, outside03, _isGreenCandleResult, s03)
outsideGreenText := createLabelText(outsideGreenText, outside04, _isGreenCandleResult, s04)
outsideGreenText := createLabelText(outsideGreenText, outside05, _isGreenCandleResult, s05)
outsideGreenText := createLabelText(outsideGreenText, outside06, _isGreenCandleResult, s06)
outsideGreenText := createLabelText(outsideGreenText, outside07, _isGreenCandleResult, s07)
outsideGreenText := createLabelText(outsideGreenText, outside08, _isGreenCandleResult, s08)
outsideGreenText := createLabelText(outsideGreenText, outside09, _isGreenCandleResult, s09)
outsideGreenText := createLabelText(outsideGreenText, outside10, _isGreenCandleResult, s10)
outsideGreenText := createLabelText(outsideGreenText, outside11, _isGreenCandleResult, s11)
outsideGreenText := createLabelText(outsideGreenText, outside12, _isGreenCandleResult, s12)
outsideGreenText := createLabelText(outsideGreenText, outside13, _isGreenCandleResult, s13)
outsideGreenText := createLabelText(outsideGreenText, outside14, _isGreenCandleResult, s14)
outsideGreenText := createLabelText(outsideGreenText, outside15, _isGreenCandleResult, s15)
outsideGreenText := createLabelText(outsideGreenText, outside16, _isGreenCandleResult, s16)
outsideGreenText := createLabelText(outsideGreenText, outside17, _isGreenCandleResult, s17)
outsideGreenText := createLabelText(outsideGreenText, outside18, _isGreenCandleResult, s18)
outsideGreenText := createLabelText(outsideGreenText, outside19, _isGreenCandleResult, s19)
outsideGreenText := createLabelText(outsideGreenText, outside20, _isGreenCandleResult, s20)
outsideGreenText := createLabelText(outsideGreenText, outside21, _isGreenCandleResult, s21)
outsideGreenText := createLabelText(outsideGreenText, outside22, _isGreenCandleResult, s22)
outsideGreenText := createLabelText(outsideGreenText, outside23, _isGreenCandleResult, s23)
outsideGreenText := createLabelText(outsideGreenText, outside24, _isGreenCandleResult, s24)
outsideGreenText := createLabelText(outsideGreenText, outside25, _isGreenCandleResult, s25)
outsideGreenText := createLabelText(outsideGreenText, outside26, _isGreenCandleResult, s26)
outsideGreenText := createLabelText(outsideGreenText, outside27, _isGreenCandleResult, s27)
outsideGreenText := createLabelText(outsideGreenText, outside28, _isGreenCandleResult, s28)
outsideGreenText := createLabelText(outsideGreenText, outside29, _isGreenCandleResult, s29)
outsideGreenText := createLabelText(outsideGreenText, outside30, _isGreenCandleResult, s30)
outsideGreenText := createLabelText(outsideGreenText, outside31, _isGreenCandleResult, s31)
outsideGreenText := createLabelText(outsideGreenText, outside32, _isGreenCandleResult, s32)
outsideGreenText := createLabelText(outsideGreenText, outside33, _isGreenCandleResult, s33)
outsideGreenText := createLabelText(outsideGreenText, outside34, _isGreenCandleResult, s34)
outsideGreenText := createLabelText(outsideGreenText, outside35, _isGreenCandleResult, s35)
outsideGreenText := createLabelText(outsideGreenText, outside36, _isGreenCandleResult, s36)
outsideGreenText := createLabelText(outsideGreenText, outside37, _isGreenCandleResult, s37)
outsideGreenText := createLabelText(outsideGreenText, outside38, _isGreenCandleResult, s38)
outsideGreenText := createLabelText(outsideGreenText, outside39, _isGreenCandleResult, s39)
outsideGreenText := createLabelText(outsideGreenText, outside40, _isGreenCandleResult, s40)

outsideRedText := createLabelText(outsideRedText, outside01, _isRedCandleResult, s01)
outsideRedText := createLabelText(outsideRedText, outside02, _isRedCandleResult, s02)
outsideRedText := createLabelText(outsideRedText, outside03, _isRedCandleResult, s03)
outsideRedText := createLabelText(outsideRedText, outside04, _isRedCandleResult, s04)
outsideRedText := createLabelText(outsideRedText, outside05, _isRedCandleResult, s05)
outsideRedText := createLabelText(outsideRedText, outside06, _isRedCandleResult, s06)
outsideRedText := createLabelText(outsideRedText, outside07, _isRedCandleResult, s07)
outsideRedText := createLabelText(outsideRedText, outside08, _isRedCandleResult, s08)
outsideRedText := createLabelText(outsideRedText, outside09, _isRedCandleResult, s09)
outsideRedText := createLabelText(outsideRedText, outside10, _isRedCandleResult, s10)
outsideRedText := createLabelText(outsideRedText, outside11, _isRedCandleResult, s11)
outsideRedText := createLabelText(outsideRedText, outside12, _isRedCandleResult, s12)
outsideRedText := createLabelText(outsideRedText, outside13, _isRedCandleResult, s13)
outsideRedText := createLabelText(outsideRedText, outside14, _isRedCandleResult, s14)
outsideRedText := createLabelText(outsideRedText, outside15, _isRedCandleResult, s15)
outsideRedText := createLabelText(outsideRedText, outside16, _isRedCandleResult, s16)
outsideRedText := createLabelText(outsideRedText, outside17, _isRedCandleResult, s17)
outsideRedText := createLabelText(outsideRedText, outside18, _isRedCandleResult, s18)
outsideRedText := createLabelText(outsideRedText, outside19, _isRedCandleResult, s19)
outsideRedText := createLabelText(outsideRedText, outside20, _isRedCandleResult, s20)
outsideRedText := createLabelText(outsideRedText, outside21, _isRedCandleResult, s21)
outsideRedText := createLabelText(outsideRedText, outside22, _isRedCandleResult, s22)
outsideRedText := createLabelText(outsideRedText, outside23, _isRedCandleResult, s23)
outsideRedText := createLabelText(outsideRedText, outside24, _isRedCandleResult, s24)
outsideRedText := createLabelText(outsideRedText, outside25, _isRedCandleResult, s25)
outsideRedText := createLabelText(outsideRedText, outside26, _isRedCandleResult, s26)
outsideRedText := createLabelText(outsideRedText, outside27, _isRedCandleResult, s27)
outsideRedText := createLabelText(outsideRedText, outside28, _isRedCandleResult, s28)
outsideRedText := createLabelText(outsideRedText, outside29, _isRedCandleResult, s29)
outsideRedText := createLabelText(outsideRedText, outside30, _isRedCandleResult, s30)
outsideRedText := createLabelText(outsideRedText, outside31, _isRedCandleResult, s31)
outsideRedText := createLabelText(outsideRedText, outside32, _isRedCandleResult, s32)
outsideRedText := createLabelText(outsideRedText, outside33, _isRedCandleResult, s33)
outsideRedText := createLabelText(outsideRedText, outside34, _isRedCandleResult, s34)
outsideRedText := createLabelText(outsideRedText, outside35, _isRedCandleResult, s35)
outsideRedText := createLabelText(outsideRedText, outside36, _isRedCandleResult, s36)
outsideRedText := createLabelText(outsideRedText, outside37, _isRedCandleResult, s37)
outsideRedText := createLabelText(outsideRedText, outside38, _isRedCandleResult, s38)
outsideRedText := createLabelText(outsideRedText, outside39, _isRedCandleResult, s39)
outsideRedText := createLabelText(outsideRedText, outside40, _isRedCandleResult, s40)


twoUpGreenText := createLabelText(twoUpGreenText, twoUp01, _isGreenCandleResult, s01)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp02, _isGreenCandleResult, s02)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp03, _isGreenCandleResult, s03)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp04, _isGreenCandleResult, s04)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp05, _isGreenCandleResult, s05)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp06, _isGreenCandleResult, s06)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp07, _isGreenCandleResult, s07)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp08, _isGreenCandleResult, s08)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp09, _isGreenCandleResult, s09)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp10, _isGreenCandleResult, s10)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp11, _isGreenCandleResult, s11)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp12, _isGreenCandleResult, s12)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp13, _isGreenCandleResult, s13)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp14, _isGreenCandleResult, s14)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp15, _isGreenCandleResult, s15)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp16, _isGreenCandleResult, s16)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp17, _isGreenCandleResult, s17)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp18, _isGreenCandleResult, s18)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp19, _isGreenCandleResult, s19)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp20, _isGreenCandleResult, s20)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp21, _isGreenCandleResult, s21)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp22, _isGreenCandleResult, s22)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp23, _isGreenCandleResult, s23)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp24, _isGreenCandleResult, s24)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp25, _isGreenCandleResult, s25)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp26, _isGreenCandleResult, s26)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp27, _isGreenCandleResult, s27)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp28, _isGreenCandleResult, s28)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp29, _isGreenCandleResult, s29)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp30, _isGreenCandleResult, s30)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp31, _isGreenCandleResult, s31)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp32, _isGreenCandleResult, s32)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp33, _isGreenCandleResult, s33)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp34, _isGreenCandleResult, s34)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp35, _isGreenCandleResult, s35)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp36, _isGreenCandleResult, s36)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp37, _isGreenCandleResult, s37)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp38, _isGreenCandleResult, s38)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp39, _isGreenCandleResult, s39)
twoUpGreenText := createLabelText(twoUpGreenText, twoUp40, _isGreenCandleResult, s40)

twoUpRedText := createLabelText(twoUpRedText, twoUp01, _isRedCandleResult, s01)
twoUpRedText := createLabelText(twoUpRedText, twoUp02, _isRedCandleResult, s02)
twoUpRedText := createLabelText(twoUpRedText, twoUp03, _isRedCandleResult, s03)
twoUpRedText := createLabelText(twoUpRedText, twoUp04, _isRedCandleResult, s04)
twoUpRedText := createLabelText(twoUpRedText, twoUp05, _isRedCandleResult, s05)
twoUpRedText := createLabelText(twoUpRedText, twoUp06, _isRedCandleResult, s06)
twoUpRedText := createLabelText(twoUpRedText, twoUp07, _isRedCandleResult, s07)
twoUpRedText := createLabelText(twoUpRedText, twoUp08, _isRedCandleResult, s08)
twoUpRedText := createLabelText(twoUpRedText, twoUp09, _isRedCandleResult, s09)
twoUpRedText := createLabelText(twoUpRedText, twoUp10, _isRedCandleResult, s10)
twoUpRedText := createLabelText(twoUpRedText, twoUp11, _isRedCandleResult, s11)
twoUpRedText := createLabelText(twoUpRedText, twoUp12, _isRedCandleResult, s12)
twoUpRedText := createLabelText(twoUpRedText, twoUp13, _isRedCandleResult, s13)
twoUpRedText := createLabelText(twoUpRedText, twoUp14, _isRedCandleResult, s14)
twoUpRedText := createLabelText(twoUpRedText, twoUp15, _isRedCandleResult, s15)
twoUpRedText := createLabelText(twoUpRedText, twoUp16, _isRedCandleResult, s16)
twoUpRedText := createLabelText(twoUpRedText, twoUp17, _isRedCandleResult, s17)
twoUpRedText := createLabelText(twoUpRedText, twoUp18, _isRedCandleResult, s18)
twoUpRedText := createLabelText(twoUpRedText, twoUp19, _isRedCandleResult, s19)
twoUpRedText := createLabelText(twoUpRedText, twoUp20, _isRedCandleResult, s20)
twoUpRedText := createLabelText(twoUpRedText, twoUp21, _isRedCandleResult, s21)
twoUpRedText := createLabelText(twoUpRedText, twoUp22, _isRedCandleResult, s22)
twoUpRedText := createLabelText(twoUpRedText, twoUp23, _isRedCandleResult, s23)
twoUpRedText := createLabelText(twoUpRedText, twoUp24, _isRedCandleResult, s24)
twoUpRedText := createLabelText(twoUpRedText, twoUp25, _isRedCandleResult, s25)
twoUpRedText := createLabelText(twoUpRedText, twoUp26, _isRedCandleResult, s26)
twoUpRedText := createLabelText(twoUpRedText, twoUp27, _isRedCandleResult, s27)
twoUpRedText := createLabelText(twoUpRedText, twoUp28, _isRedCandleResult, s28)
twoUpRedText := createLabelText(twoUpRedText, twoUp29, _isRedCandleResult, s29)
twoUpRedText := createLabelText(twoUpRedText, twoUp30, _isRedCandleResult, s30)
twoUpRedText := createLabelText(twoUpRedText, twoUp31, _isRedCandleResult, s31)
twoUpRedText := createLabelText(twoUpRedText, twoUp32, _isRedCandleResult, s32)
twoUpRedText := createLabelText(twoUpRedText, twoUp33, _isRedCandleResult, s33)
twoUpRedText := createLabelText(twoUpRedText, twoUp34, _isRedCandleResult, s34)
twoUpRedText := createLabelText(twoUpRedText, twoUp35, _isRedCandleResult, s35)
twoUpRedText := createLabelText(twoUpRedText, twoUp36, _isRedCandleResult, s36)
twoUpRedText := createLabelText(twoUpRedText, twoUp37, _isRedCandleResult, s37)
twoUpRedText := createLabelText(twoUpRedText, twoUp38, _isRedCandleResult, s38)
twoUpRedText := createLabelText(twoUpRedText, twoUp39, _isRedCandleResult, s39)
twoUpRedText := createLabelText(twoUpRedText, twoUp40, _isRedCandleResult, s40)

twoDownGreenText := createLabelText(twoDownGreenText, twoDown01, _isGreenCandleResult, s01)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown02, _isGreenCandleResult, s02)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown03, _isGreenCandleResult, s03)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown04, _isGreenCandleResult, s04)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown05, _isGreenCandleResult, s05)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown06, _isGreenCandleResult, s06)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown07, _isGreenCandleResult, s07)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown08, _isGreenCandleResult, s08)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown09, _isGreenCandleResult, s09)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown10, _isGreenCandleResult, s10)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown11, _isGreenCandleResult, s11)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown12, _isGreenCandleResult, s12)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown13, _isGreenCandleResult, s13)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown14, _isGreenCandleResult, s14)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown15, _isGreenCandleResult, s15)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown16, _isGreenCandleResult, s16)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown17, _isGreenCandleResult, s17)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown18, _isGreenCandleResult, s18)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown19, _isGreenCandleResult, s19)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown20, _isGreenCandleResult, s20)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown21, _isGreenCandleResult, s21)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown22, _isGreenCandleResult, s22)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown23, _isGreenCandleResult, s23)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown24, _isGreenCandleResult, s24)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown25, _isGreenCandleResult, s25)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown26, _isGreenCandleResult, s26)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown27, _isGreenCandleResult, s27)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown28, _isGreenCandleResult, s28)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown29, _isGreenCandleResult, s29)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown30, _isGreenCandleResult, s30)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown31, _isGreenCandleResult, s31)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown32, _isGreenCandleResult, s32)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown33, _isGreenCandleResult, s33)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown34, _isGreenCandleResult, s34)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown35, _isGreenCandleResult, s35)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown36, _isGreenCandleResult, s36)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown37, _isGreenCandleResult, s37)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown38, _isGreenCandleResult, s38)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown39, _isGreenCandleResult, s39)
twoDownGreenText := createLabelText(twoDownGreenText, twoDown40, _isGreenCandleResult, s40)

twoDownRedText := createLabelText(twoDownRedText, twoDown01, _isRedCandleResult, s01)
twoDownRedText := createLabelText(twoDownRedText, twoDown02, _isRedCandleResult, s02)
twoDownRedText := createLabelText(twoDownRedText, twoDown03, _isRedCandleResult, s03)
twoDownRedText := createLabelText(twoDownRedText, twoDown04, _isRedCandleResult, s04)
twoDownRedText := createLabelText(twoDownRedText, twoDown05, _isRedCandleResult, s05)
twoDownRedText := createLabelText(twoDownRedText, twoDown06, _isRedCandleResult, s06)
twoDownRedText := createLabelText(twoDownRedText, twoDown07, _isRedCandleResult, s07)
twoDownRedText := createLabelText(twoDownRedText, twoDown08, _isRedCandleResult, s08)
twoDownRedText := createLabelText(twoDownRedText, twoDown09, _isRedCandleResult, s09)
twoDownRedText := createLabelText(twoDownRedText, twoDown10, _isRedCandleResult, s10)
twoDownRedText := createLabelText(twoDownRedText, twoDown11, _isRedCandleResult, s11)
twoDownRedText := createLabelText(twoDownRedText, twoDown12, _isRedCandleResult, s12)
twoDownRedText := createLabelText(twoDownRedText, twoDown13, _isRedCandleResult, s13)
twoDownRedText := createLabelText(twoDownRedText, twoDown14, _isRedCandleResult, s14)
twoDownRedText := createLabelText(twoDownRedText, twoDown15, _isRedCandleResult, s15)
twoDownRedText := createLabelText(twoDownRedText, twoDown16, _isRedCandleResult, s16)
twoDownRedText := createLabelText(twoDownRedText, twoDown17, _isRedCandleResult, s17)
twoDownRedText := createLabelText(twoDownRedText, twoDown18, _isRedCandleResult, s18)
twoDownRedText := createLabelText(twoDownRedText, twoDown19, _isRedCandleResult, s19)
twoDownRedText := createLabelText(twoDownRedText, twoDown20, _isRedCandleResult, s20)
twoDownRedText := createLabelText(twoDownRedText, twoDown21, _isRedCandleResult, s21)
twoDownRedText := createLabelText(twoDownRedText, twoDown22, _isRedCandleResult, s22)
twoDownRedText := createLabelText(twoDownRedText, twoDown23, _isRedCandleResult, s23)
twoDownRedText := createLabelText(twoDownRedText, twoDown24, _isRedCandleResult, s24)
twoDownRedText := createLabelText(twoDownRedText, twoDown25, _isRedCandleResult, s25)
twoDownRedText := createLabelText(twoDownRedText, twoDown26, _isRedCandleResult, s26)
twoDownRedText := createLabelText(twoDownRedText, twoDown27, _isRedCandleResult, s27)
twoDownRedText := createLabelText(twoDownRedText, twoDown28, _isRedCandleResult, s28)
twoDownRedText := createLabelText(twoDownRedText, twoDown29, _isRedCandleResult, s29)
twoDownRedText := createLabelText(twoDownRedText, twoDown30, _isRedCandleResult, s30)
twoDownRedText := createLabelText(twoDownRedText, twoDown31, _isRedCandleResult, s31)
twoDownRedText := createLabelText(twoDownRedText, twoDown32, _isRedCandleResult, s32)
twoDownRedText := createLabelText(twoDownRedText, twoDown33, _isRedCandleResult, s33)
twoDownRedText := createLabelText(twoDownRedText, twoDown34, _isRedCandleResult, s34)
twoDownRedText := createLabelText(twoDownRedText, twoDown35, _isRedCandleResult, s35)
twoDownRedText := createLabelText(twoDownRedText, twoDown36, _isRedCandleResult, s36)
twoDownRedText := createLabelText(twoDownRedText, twoDown37, _isRedCandleResult, s37)
twoDownRedText := createLabelText(twoDownRedText, twoDown38, _isRedCandleResult, s38)
twoDownRedText := createLabelText(twoDownRedText, twoDown39, _isRedCandleResult, s39)
twoDownRedText := createLabelText(twoDownRedText, twoDown40, _isRedCandleResult, s40)


// PLOT LABELS
// Set this up so it will display all of them spead across, easier for visbility IMO
twoUpLabel = label.new(
          x         =_labelXIndex-_labelIndexOffset*5,
          y         = _labelYIndex,
          text      = createFinalFormattedLabelText(_labelTwoUpText, twoUpGreenText,twoUpRedText),
          color     = color.green,
          textcolor = _labelTextColor,
          style     = _labelStyle,
          yloc      = _labelYLoc,
          textalign = _labelTextAlign)
label.delete(twoUpLabel[1])

labelTwoDown = label.new(
          x         = _labelXIndex -_labelIndexOffset * 4,
          y         = _labelYIndex,
          text      = createFinalFormattedLabelText(_labelTwoDownText, twoDownGreenText, twoDownRedText),
          color     = color.red,
          textcolor = _labelTextColor,
          style     = _labelStyle,
          yloc      = _labelYLoc,
          textalign = _labelTextAlign)
label.delete(labelTwoDown[1])

labelOutSide = label.new(
          x         = _labelXIndex -_labelIndexOffset * 3,
          y         = _labelYIndex,
          text      = createFinalFormattedLabelText(_labelOutsideText, outsideGreenText,outsideRedText),
          color     = color.fuchsia,
          textcolor = _labelTextColor,
          style     = _labelStyle,
          textalign = _labelTextAlign)
label.delete(labelOutSide[1])

labelInside = label.new(
          x         = _labelXIndex - _labelIndexOffset * 2,
          y         = _labelYIndex,
          text      = _labelHeaderText + _labelInsideText + insideText,
          color     = color.new(#F6BE00, 0),
          textcolor = _labelTextColor,
          style     = _labelStyle,
          yloc      = _labelYLoc,
          textalign = _labelTextAlign)
label.delete(labelInside[1])

labelHammer = label.new(
          x         = _labelXIndex - _labelIndexOffset * 1,
          y         = _labelYIndex,
          text      = createFinalFormattedLabelText(_labelHammerText, hammerGreenText, hammerRedText),
          color     = color.green,
          textcolor = _labelTextColor,
          style     = _labelStyle,
          yloc      = _labelYLoc,
          textalign = _labelTextAlign)
label.delete(labelHammer[1])

labelShooter = label.new(
           x         = _labelXIndex,
           y         = _labelYIndex,
           text      = createFinalFormattedLabelText(_labelShooterText, shooterGreenText,shooterRedText),
           color     = color.red,
           textcolor = _labelTextColor,
           style     = _labelStyle,
           yloc      = _labelYLoc,
           textalign = _labelTextAlign)
label.delete(labelShooter[1])
